window.DASH = window.DASH || {};
window.DASH.abruzzo = {
  meta: {
    nome: "Abruzzo",
    area: "Sud e Isole",
    presidente: "Marco Marsilio",
    maggioranza: "centrodestra",
    stemma: "🐻"
  },
  ui: {
    h1: "Abruzzo — Programma vs Realtà",
    sub: "Monitoraggio di 6 indicatori (4 comuni + 2 specifici) del programma della giunta Marsilio II, in carica da marzo 2024.",
    metaHtml: "Dati aggiornati a <b>luglio 2026</b> · Fonti: Ministero della Salute, ISTAT, ISPRA, Ministero dell'Interno · <b>Il valore (KPI) è misurato; lo «stato» è una valutazione. Correlazione ≠ causalità.</b>",
    searchPlaceholder: "Cerca indicatore…",
    chipsAll: "Tutte le aree",
    hint: "Clicca una scheda per aprire dettaglio, nota e fonte.",
    emptyMsg: "Nessun indicatore corrisponde ai filtri.",
    startLabel: "Punto di partenza",
    noteLabel: "Nota",
    sourceLabel: "Fonte",
    footerHtml: "<p><b>Metodologia.</b> Quattro stati: <span style='color:var(--green)'>In linea</span> (obiettivo raggiunto), <span style='color:var(--blue)'>In corso</span> (progressi coerenti con l'impegno), <span style='color:var(--amber)'>In ritardo</span> (progressi insufficienti), <span style='color:var(--red)'>Fermo</span> (nessun progresso misurabile). Gli indicatori misurano il contesto regionale: l'andamento non è attribuibile per intero all'azione della giunta (correlazione ≠ causalità). Dove indicato, i valori sono stime; i dati mancanti sono dichiarati.</p>"
  },
  status: {
    "in-linea": { label: "In linea",  cls: "s-green" },
    "in-corso": { label: "In corso",  cls: "s-blue"  },
    "ritardo":  { label: "In ritardo", cls: "s-amber" },
    "fermo":    { label: "Fermo",     cls: "s-red"   }
  },
  items: [
    { area:"Sanità", title:"Riportare i LEA alla sufficienza",
      promise:"Il programma Marsilio II promette il risanamento dei conti sanitari e il potenziamento di prevenzione e territorio.",
      cur:"1/3", curLbl:"macro-aree LEA sopra la soglia di sufficienza (2023)", base:"insufficienze in prevenzione e distrettuale",
      delta:"2 aree critiche", deltaCls:"up-bad", deltaSub:"prevenzione e distrettuale", barPct:30, barCol:"var(--red)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Nel monitoraggio LEA 2023 l'Abruzzo è insufficiente in due macro-aree su tre (prevenzione e distrettuale). I disavanzi delle ASL hanno imposto manovre di rientro nel 2024-2025: la sanità è il principale fronte critico della legislatura.",
      src:"Ministero della Salute — Nuovo Sistema di Garanzia", url:"https://www.salute.gov.it/new/it/news-e-media/notizie/livelli-essenziali-di-assistenza-sintesi-dei-risultati-del-nuovo-sistema-di/", asof:"2023 (relazione 2025)" },
    { area:"Sicurezza", title:"Territorio sotto la media per reati",
      promise:"Impegni su sicurezza urbana sulla costa e nelle aree interne.",
      cur:"≈3.000", curLbl:"delitti denunciati ogni 100.000 abitanti (2022, stima)", base:"media Italia: ≈3.800 ogni 100.000",
      delta:"-21% vs Italia", deltaCls:"up-good", deltaSub:"sotto la media nazionale", barPct:72, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Denunce sotto la media nazionale, con valori più alti sulla costa pescarese. Valore stimato e arrotondato su dati ISTAT/Ministero dell'Interno 2022.",
      src:"ISTAT — Delitti denunciati", url:"http://dati.istat.it/Index.aspx?DataSetCode=dccv_delittips", asof:"2022 (stima)" },
    { area:"Lavoro", title:"Occupazione da riallineare al Centro-Nord",
      promise:"Il programma punta su ZES unica, automotive (Stellantis Atessa) e turismo per creare lavoro stabile.",
      cur:"58,9%", curLbl:"tasso di occupazione 15-64 anni (2023, arrotondato)", base:"media Italia: 61,5% (2023)",
      delta:"-2,6 pt vs Italia", deltaCls:"up-bad", deltaSub:"migliore del Mezzogiorno", barPct:59, barCol:"var(--amber)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"L'Abruzzo ha il tasso di occupazione più alto del Mezzogiorno ma resta sotto la media nazionale. Il polo automotive di Atessa (Stellantis) è il principale datore di lavoro privato e la sua transizione elettrica è il rischio industriale numero uno. Valore arrotondato.",
      src:"ISTAT — Rilevazione sulle forze di lavoro", url:"https://noi-italia.istat.it/pagina.php?id=3&categoria=16&action=show&L=0", asof:"2023" },
    { area:"Ambiente", title:"Differenziata intorno all'obiettivo di legge",
      promise:"Impegni su economia circolare, parchi (la regione dei parchi) e costa.",
      cur:"≈65%", curLbl:"raccolta differenziata (2022, stima)", base:"obiettivo di legge: 65%",
      delta:"al limite", deltaCls:"up-good", deltaSub:"intorno alla soglia di legge", barPct:65, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"La raccolta differenziata abruzzese è intorno alla soglia del 65% (valore stimato: il dato puntuale 2022-2023 è nel Catasto rifiuti ISPRA). Un terzo del territorio è protetto da parchi nazionali e regionali, primato italiano.",
      src:"ISPRA — Catasto rifiuti", url:"https://www.catasto-rifiuti.isprambiente.it/", asof:"2022 (stima)" },
    { area:"Trasporti", title:"Roma-Pescara: la ferrovia promessa",
      promise:"Opera simbolo del mandato Marsilio: velocizzare il collegamento ferroviario Roma-Pescara con i fondi PNRR.",
      cur:"lotti parziali", curLbl:"cantieri avviati solo su alcune tratte", base:"promessa iniziale: Roma-Pescara sotto le 3 ore",
      delta:"ridimensionata", deltaCls:"up-bad", deltaSub:"progetto ridotto rispetto agli annunci", barPct:25, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Il progetto di velocizzazione Roma-Pescara è stato ridimensionato rispetto agli annunci iniziali: i lotti finanziati (PNRR e fondi ordinari RFI) coprono solo parte del tracciato e i tempi si sono allungati, tra ricorsi dei territori e revisioni progettuali.",
      src:"RFI — potenziamento Roma-Pescara", url:"https://www.rfi.it/", asof:"2025" },
    { area:"Aree interne", title:"Fermare lo spopolamento delle aree interne",
      promise:"Il programma promette borghi ripopolati, servizi nelle aree montane e ricostruzione post-sisma 2009/2016 completata.",
      cur:"saldo negativo", curLbl:"popolazione delle aree interne ancora in calo", base:"decenni di spopolamento montano",
      delta:"trend invariato", deltaCls:"up-bad", deltaSub:"nessuna inversione misurabile", barPct:15, barCol:"var(--red)",
      status:"fermo", badge:"Fermo", bCls:"b-red",
      note:"Nonostante incentivi e fondi di coesione, i comuni montani abruzzesi continuano a perdere residenti (dati demografici ISTAT). La ricostruzione post-sisma procede (L'Aquila in fase avanzata, cratere 2016 più indietro), ma l'inversione demografica promessa non è misurabile.",
      src:"ISTAT — Indicatori demografici", url:"https://demo.istat.it/", asof:"2024" }
  ]
};
