window.DASH = window.DASH || {};
window.DASH.basilicata = {
  meta: {
    nome: "Basilicata",
    area: "Sud e Isole",
    presidente: "Vito Bardi",
    maggioranza: "centrodestra",
    stemma: "🏔️"
  },
  ui: {
    h1: "Basilicata — Programma vs Realtà",
    sub: "Monitoraggio di 6 indicatori (4 comuni + 2 specifici) del programma della giunta Bardi II, in carica da aprile 2024.",
    metaHtml: "Dati aggiornati a <b>luglio 2026</b> · Fonti: Ministero della Salute, ISTAT, ISPRA, Ministero dell'Interno · <b>Il valore (KPI) è misurato; lo «stato» è una valutazione. Correlazione ≠ causalità.</b>",
    searchPlaceholder: "Cerca indicatore…",
    chipsAll: "Tutte le aree",
    hint: "Clicca una scheda per aprire dettaglio, nota e fonte.",
    emptyMsg: "Nessun indicatore corrisponde ai filtri.",
    startLabel: "Punto di partenza",
    noteLabel: "Nota",
    sourceLabel: "Fonte",
    footerHtml: "<p><b>Metodologia.</b> Quattro stati: <span style='color:var(--green)'>In linea</span> (obiettivo raggiunto), <span style='color:var(--blue)'>In corso</span> (progressi coerenti con l'impegno), <span style='color:var(--amber)'>In ritardo</span> (progressi insufficienti), <span style='color:var(--red)'>Fermo</span> (nessun progresso misurabile). Gli indicatori misurano il contesto regionale: l'andamento non è attribuibile per intero all'azione della giunta (correlazione ≠ causalità). Dove indicato, i valori sono stime; i dati mancanti sono dichiarati.</p>"
  },
  status: {
    "in-linea": { label: "In linea",  cls: "s-green" },
    "in-corso": { label: "In corso",  cls: "s-blue"  },
    "ritardo":  { label: "In ritardo", cls: "s-amber" },
    "fermo":    { label: "Fermo",     cls: "s-red"   }
  },
  items: [
    { area:"Sanità", title:"Recuperare la sufficienza nell'assistenza territoriale",
      promise:"Il programma Bardi II promette il potenziamento della sanità territoriale e la riduzione della mobilità passiva verso le regioni vicine.",
      cur:"2/3", curLbl:"macro-aree LEA sopra la soglia di sufficienza (2023)", base:"insufficienza nell'area distrettuale",
      delta:"1 area critica", deltaCls:"up-bad", deltaSub:"distrettuale sotto soglia", barPct:48, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Nel monitoraggio LEA 2023 la Basilicata resta sotto soglia nella macro-area distrettuale (assistenza territoriale). La dispersione della popolazione su un territorio montano rende strutturalmente difficile garantire servizi di prossimità.",
      src:"Ministero della Salute — Nuovo Sistema di Garanzia", url:"https://www.salute.gov.it/new/it/news-e-media/notizie/livelli-essenziali-di-assistenza-sintesi-dei-risultati-del-nuovo-sistema-di/", asof:"2023 (relazione 2025)" },
    { area:"Sicurezza", title:"Tra i territori più sicuri d'Italia",
      promise:"Mantenere bassa la criminalità e presidiare le aree interne.",
      cur:"≈2.300", curLbl:"delitti denunciati ogni 100.000 abitanti (2022, stima)", base:"media Italia: ≈3.800 ogni 100.000",
      delta:"-39% vs Italia", deltaCls:"up-good", deltaSub:"tra i valori più bassi", barPct:88, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"La Basilicata registra uno dei tassi di denuncia più bassi d'Italia. Valore stimato e arrotondato su dati ISTAT/Ministero dell'Interno 2022; i piccoli numeri rendono il tasso volatile.",
      src:"ISTAT — Delitti denunciati", url:"http://dati.istat.it/Index.aspx?DataSetCode=dccv_delittips", asof:"2022 (stima)" },
    { area:"Lavoro", title:"Lavoro oltre il petrolio e l'automotive",
      promise:"Il programma punta su diversificazione: ZES unica, agroalimentare e turismo accanto a estrazioni (Val d'Agri) e Stellantis Melfi.",
      cur:"54,0%", curLbl:"tasso di occupazione 15-64 anni (2023, arrotondato)", base:"media Italia: 61,5% (2023)",
      delta:"-7,5 pt vs Italia", deltaCls:"up-bad", deltaSub:"sotto la media nazionale", barPct:54, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Occupazione sotto la media nazionale. La transizione elettrica dello stabilimento Stellantis di Melfi — primo datore di lavoro privato regionale — è la variabile decisiva del quinquennio. Valore arrotondato: verificare su dati.istat.it.",
      src:"ISTAT — Rilevazione sulle forze di lavoro", url:"https://noi-italia.istat.it/pagina.php?id=3&categoria=16&action=show&L=0", asof:"2023" },
    { area:"Ambiente", title:"Differenziata sotto l'obiettivo di legge",
      promise:"Impegni su ciclo dei rifiuti e monitoraggio ambientale delle aree petrolifere.",
      cur:"≈58%", curLbl:"raccolta differenziata (2022, stima)", base:"obiettivo di legge: 65%",
      delta:"≈-7 pt vs obiettivo", deltaCls:"up-bad", deltaSub:"sotto la soglia di legge", barPct:58, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"La raccolta differenziata lucana resta sotto l'obiettivo del 65% (valore stimato: il dato puntuale è nel Catasto rifiuti ISPRA). Il monitoraggio ambientale delle estrazioni in Val d'Agri resta il dossier più sensibile.",
      src:"ISPRA — Catasto rifiuti", url:"https://www.catasto-rifiuti.isprambiente.it/", asof:"2022 (stima)" },
    { area:"Energia", title:"Trasformare il petrolio in bollette più leggere",
      promise:"Misura bandiera di Bardi: usare le compensazioni delle estrazioni per azzerare la spesa del gas dei residenti (bonus gas) e ora per l'acqua.",
      cur:"attivo", curLbl:"bonus gas regionale per i residenti in vigore", base:"avviato nel 2022-2023 con le royalties del gas",
      delta:"misura confermata", deltaCls:"up-good", deltaSub:"estesa nel secondo mandato", barPct:75, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Il contributo regionale sul gas (finanziato dalle compensazioni delle compagnie estrattive) è operativo e ha ridotto la spesa delle famiglie lucane; nel secondo mandato la giunta lo ha affiancato con misure sull'acqua. I risparmi effettivi variano per famiglia e annata.",
      src:"Regione Basilicata — bonus gas", url:"https://www.regione.basilicata.it/", asof:"2025" },
    { area:"Spopolamento", title:"Frenare l'esodo demografico",
      promise:"Il programma promette residenzialità e servizi per trattenere giovani e famiglie in una regione sotto i 540 mila abitanti.",
      cur:"in calo", curLbl:"popolazione residente, trend negativo continuo", base:"≈578 mila residenti nel 2013",
      delta:"esodo giovanile", deltaCls:"up-bad", deltaSub:"nessuna inversione misurabile", barPct:12, barCol:"var(--red)",
      status:"fermo", badge:"Fermo", bCls:"b-red",
      note:"La Basilicata continua a perdere popolazione, soprattutto giovani laureati (dati demo.istat.it e rapporti SVIMEZ). Nessuna misura regionale ha finora invertito il trend; Matera resta l'unica area con dinamiche meno negative.",
      src:"ISTAT — Bilancio demografico", url:"https://demo.istat.it/", asof:"2024" }
  ]
};
