window.DASH = window.DASH || {};
window.DASH.calabria = {
  meta: {
    nome: "Calabria",
    area: "Sud e Isole",
    presidente: "Roberto Occhiuto",
    maggioranza: "centrodestra",
    stemma: "🌲"
  },
  ui: {
    h1: "Calabria — Programma vs Realtà",
    sub: "Monitoraggio di 6 indicatori (4 comuni + 2 specifici) del programma della giunta Occhiuto II, rieletta a ottobre 2025 (57,3% dei voti).",
    metaHtml: "Dati aggiornati a <b>luglio 2026</b> · Fonti: Ministero della Salute, ISTAT, ISPRA, Ministero dell'Interno · <b>Il valore (KPI) è misurato; lo «stato» è una valutazione. Correlazione ≠ causalità.</b>",
    searchPlaceholder: "Cerca indicatore…",
    chipsAll: "Tutte le aree",
    hint: "Clicca una scheda per aprire dettaglio, nota e fonte.",
    emptyMsg: "Nessun indicatore corrisponde ai filtri.",
    startLabel: "Punto di partenza",
    noteLabel: "Nota",
    sourceLabel: "Fonte",
    footerHtml: "<p><b>Metodologia.</b> Quattro stati: <span style='color:var(--green)'>In linea</span> (obiettivo raggiunto), <span style='color:var(--blue)'>In corso</span> (progressi coerenti con l'impegno), <span style='color:var(--amber)'>In ritardo</span> (progressi insufficienti), <span style='color:var(--red)'>Fermo</span> (nessun progresso misurabile). Gli indicatori misurano il contesto regionale: l'andamento non è attribuibile per intero all'azione della giunta (correlazione ≠ causalità). Dove indicato, i valori sono stime; i dati mancanti sono dichiarati.</p>"
  },
  status: {
    "in-linea": { label: "In linea",  cls: "s-green" },
    "in-corso": { label: "In corso",  cls: "s-blue"  },
    "ritardo":  { label: "In ritardo", cls: "s-amber" },
    "fermo":    { label: "Fermo",     cls: "s-red"   }
  },
  items: [
    { area:"Sanità", title:"Uscire dal commissariamento sanitario",
      promise:"Occhiuto (commissario ad acta della sanità calabrese) promette da due mandati il risanamento: conti in ordine, medici assunti (anche da Cuba) e LEA garantiti.",
      cur:"2/3", curLbl:"macro-aree LEA sopra la soglia di sufficienza (2023)", base:"regione commissariata dal 2010, a lungo ultima nei LEA",
      delta:"1 area critica", deltaCls:"up-bad", deltaSub:"distrettuale sotto soglia", barPct:45, barCol:"var(--amber)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Nel monitoraggio LEA 2023 la Calabria resta sotto soglia nell'area distrettuale, ma il quadro è in miglioramento rispetto agli anni in cui era insufficiente ovunque. Emigrazione sanitaria e pronto soccorso restano le criticità più gravi d'Italia.",
      src:"Ministero della Salute — Nuovo Sistema di Garanzia", url:"https://www.salute.gov.it/new/it/news-e-media/notizie/livelli-essenziali-di-assistenza-sintesi-dei-risultati-del-nuovo-sistema-di/", asof:"2023 (relazione 2025)" },
    { area:"Sicurezza", title:"Poche denunce, presenza della 'ndrangheta",
      promise:"Impegni su legalità, beni confiscati e contrasto alla criminalità organizzata a fianco dello Stato.",
      cur:"≈2.800", curLbl:"delitti denunciati ogni 100.000 abitanti (2022)", base:"media Italia: ≈3.800 ogni 100.000",
      delta:"-26% vs Italia", deltaCls:"up-good", deltaSub:"dato da leggere con cautela", barPct:60, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Le denunce per abitante sono tra le più basse d'Italia (2,8 ogni 100 nel 2022), ma il dato sottostima la criminalità reale: la presenza della 'ndrangheta e la bassa propensione alla denuncia distorcono il confronto con le altre regioni.",
      src:"ISTAT — Delitti denunciati (elab. Pagella Politica)", url:"https://pagellapolitica.it/articoli/mappe-denunce-reati-forze-ordine-italia", asof:"2022" },
    { area:"Lavoro", title:"Risalire dall'ultimo posto per occupazione",
      promise:"Il programma punta su ZES unica, porto di Gioia Tauro e turismo per creare lavoro stabile.",
      cur:"44,6%", curLbl:"tasso di occupazione 15-64 anni (2023)", base:"media Italia: 61,5% (2023)",
      delta:"-16,9 pt vs Italia", deltaCls:"up-bad", deltaSub:"penultima in Italia", barPct:45, barCol:"var(--red)",
      status:"fermo", badge:"Fermo", bCls:"b-red",
      note:"La Calabria resta penultima in Italia per tasso di occupazione (44,6% nel 2023, davanti alla sola Campania), con la più alta emigrazione giovanile in rapporto alla popolazione. Il porto di Gioia Tauro, primo transhipment d'Italia, resta un'enclave con ricadute occupazionali limitate.",
      src:"ISTAT — Rilevazione sulle forze di lavoro", url:"https://noi-italia.istat.it/pagina.php?id=3&categoria=16&action=show&L=0", asof:"2023" },
    { area:"Ambiente", title:"Differenziata e depurazione: doppio ritardo",
      promise:"Il programma promette la chiusura del ciclo dei rifiuti e mare pulito con il piano sulla depurazione.",
      cur:"54,6%", curLbl:"raccolta differenziata (2022)", base:"obiettivo di legge: 65%",
      delta:"-10,4 pt vs obiettivo", deltaCls:"up-bad", deltaSub:"tra le ultime in Italia", barPct:55, barCol:"var(--red)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Raccolta differenziata tra le più basse d'Italia e sistema di depurazione delle acque reflue oggetto di infrazione europea. La giunta rivendica il piano straordinario depurazione avviato con fondi europei: risultati misurabili sulle acque di balneazione richiedono anni.",
      src:"ISPRA — Rapporto Rifiuti Urbani", url:"https://www.isprambiente.gov.it/it/istituto-informa/comunicati-stampa/anno-2024/rifiuti-urbani-nel-2023-cresce-dello-0-7-la-produzione", asof:"2022" },
    { area:"Aeroporti", title:"Il rilancio degli aeroporti calabresi",
      promise:"Risultato rivendicato dal primo mandato Occhiuto e rilanciato nel secondo: nuove rotte (anche Ryanair) e record di passeggeri negli scali di Lamezia, Reggio e Crotone.",
      cur:"record", curLbl:"passeggeri annui ai massimi storici nei 3 scali", base:"≈3 mln di passeggeri complessivi pre-2022",
      delta:"forte crescita", deltaCls:"up-good", deltaSub:"Reggio Calabria rilanciata", barPct:80, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Dopo gli accordi con le compagnie low cost, il sistema aeroportuale calabrese ha superato i record storici di traffico (oltre 4 milioni di passeggeri complessivi nel 2024 secondo i comunicati di SACAL e Assaeroporti; valore stimato). L'effetto su turismo e collegamenti è l'argomento forte della giunta.",
      src:"SACAL / Assaeroporti — dati di traffico", url:"https://www.assaeroporti.com/statistiche/", asof:"2024 (stima)" },
    { area:"Depurazione e mare", title:"Un mare finalmente balneabile",
      promise:"Promessa simbolo di Occhiuto: risolvere il problema storico della depurazione e rendere la costa calabrese balneabile ovunque.",
      cur:"parziale", curLbl:"depuratori riammodernati, infrazione UE ancora aperta", base:"decine di agglomerati in infrazione europea a inizio mandato",
      delta:"cantieri avviati", deltaCls:"up-good", deltaSub:"risultati non ancora consolidati", barPct:40, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Il piano regionale sulla depurazione ha finanziato interventi su decine di impianti e la qualità delle acque di balneazione è migliorata in diversi tratti (dati ARPACAL), ma numerosi agglomerati restano in procedura di infrazione UE: il numero esatto aggiornato non è disponibile in forma consolidata.",
      src:"ARPACAL — acque di balneazione", url:"https://www.arpacal.it/", asof:"2025" }
  ]
};
