window.DASH = window.DASH || {};
window.DASH.campania = {
  meta: {
    nome: "Campania",
    area: "Sud e Isole",
    presidente: "Roberto Fico",
    maggioranza: "centrosinistra (M5S-PD e alleati)",
    stemma: "🌋"
  },
  ui: {
    h1: "Campania — Programma vs Realtà",
    sub: "Monitoraggio di 6 indicatori (4 comuni + 2 specifici) del programma della giunta Fico, eletta a novembre 2025 (60,6% dei voti) dopo i dieci anni di De Luca.",
    metaHtml: "Dati aggiornati a <b>luglio 2026</b> · Fonti: Ministero della Salute, ISTAT, ISPRA, Ministero dell'Interno · <b>Il valore (KPI) è misurato; lo «stato» è una valutazione. Correlazione ≠ causalità.</b>",
    searchPlaceholder: "Cerca indicatore…",
    chipsAll: "Tutte le aree",
    hint: "Clicca una scheda per aprire dettaglio, nota e fonte.",
    emptyMsg: "Nessun indicatore corrisponde ai filtri.",
    startLabel: "Punto di partenza",
    noteLabel: "Nota",
    sourceLabel: "Fonte",
    footerHtml: "<p><b>Metodologia.</b> Quattro stati: <span style='color:var(--green)'>In linea</span> (obiettivo raggiunto), <span style='color:var(--blue)'>In corso</span> (progressi coerenti con l'impegno), <span style='color:var(--amber)'>In ritardo</span> (progressi insufficienti), <span style='color:var(--red)'>Fermo</span> (nessun progresso misurabile). La giunta è in carica da pochi mesi: molti indicatori fotografano l'eredità della gestione precedente. Correlazione ≠ causalità. Dove indicato, i valori sono stime; i dati mancanti sono dichiarati.</p>"
  },
  status: {
    "in-linea": { label: "In linea",  cls: "s-green" },
    "in-corso": { label: "In corso",  cls: "s-blue"  },
    "ritardo":  { label: "In ritardo", cls: "s-amber" },
    "fermo":    { label: "Fermo",     cls: "s-red"   }
  },
  items: [
    { area:"Sanità", title:"Sanità pubblica: la promessa fondativa di Fico",
      promise:"Primo punto del programma Fico: rilanciare la sanità pubblica campana, ridurre le liste d'attesa e la mobilità passiva verso il Nord.",
      cur:"3/3", curLbl:"macro-aree LEA sopra la soglia di sufficienza (2023)", base:"Regione a lungo inadempiente, uscita dal commissariamento nel 2019",
      delta:"adempiente", deltaCls:"up-good", deltaSub:"punteggi ancora bassi in graduatoria", barPct:60, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"La Campania supera la soglia in tutte le macro-aree LEA 2023 — un progresso storico — ma con punteggi tra i più bassi delle regioni adempienti; spesa sanitaria pro capite e mobilità passiva restano critiche. La nuova giunta si misura da qui.",
      src:"Ministero della Salute — Nuovo Sistema di Garanzia", url:"https://www.salute.gov.it/new/it/news-e-media/notizie/livelli-essenziali-di-assistenza-sintesi-dei-risultati-del-nuovo-sistema-di/", asof:"2023 (relazione 2025)" },
    { area:"Sicurezza", title:"Contrasto alla criminalità organizzata e giovanile",
      promise:"Impegni su sicurezza urbana a Napoli, contrasto alle baby gang e riqualificazione delle periferie (Caivano come modello nazionale).",
      cur:"≈3.500", curLbl:"delitti denunciati ogni 100.000 abitanti (2022, stima)", base:"media Italia: ≈3.800 ogni 100.000",
      delta:"-8% vs Italia", deltaCls:"up-good", deltaSub:"ma con più reati violenti", barPct:50, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Le denunce totali per abitante sono sotto la media nazionale, ma la Campania resta prima per alcune categorie gravi (rapine, reati di camorra) e la propensione alla denuncia è più bassa. Valore stimato su dati ISTAT 2022: il confronto tra territori va fatto con cautela.",
      src:"ISTAT — Delitti denunciati", url:"http://dati.istat.it/Index.aspx?DataSetCode=dccv_delittips", asof:"2022 (stima)" },
    { area:"Lavoro", title:"Il tasso di occupazione più basso d'Italia",
      promise:"Il programma Fico promette lavoro stabile e formazione per i giovani, con strumenti regionali di sostegno al reddito e all'occupazione.",
      cur:"44,4%", curLbl:"tasso di occupazione 15-64 anni (2023)", base:"media Italia: 61,5% (2023)",
      delta:"-17,1 pt vs Italia", deltaCls:"up-bad", deltaSub:"ultima in Italia", barPct:44, barCol:"var(--red)",
      status:"fermo", badge:"Fermo", bCls:"b-red",
      note:"La Campania ha il tasso di occupazione più basso d'Italia (44,4% nel 2023), con disoccupazione giovanile e femminile ai massimi europei. Il 2024 ha mostrato segnali di recupero nel Mezzogiorno, ma il divario resta oltre 15 punti dalla media.",
      src:"ISTAT — Rilevazione sulle forze di lavoro", url:"https://noi-italia.istat.it/pagina.php?id=3&categoria=16&action=show&L=0", asof:"2023" },
    { area:"Ambiente", title:"Differenziata sotto l'obiettivo, Terra dei Fuochi aperta",
      promise:"Il programma promette la chiusura del ciclo dei rifiuti, bonifiche nella Terra dei Fuochi e depurazione del litorale domizio.",
      cur:"55,6%", curLbl:"raccolta differenziata (2022)", base:"obiettivo di legge: 65%",
      delta:"-9,4 pt vs obiettivo", deltaCls:"up-bad", deltaSub:"sotto la soglia di legge", barPct:56, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"La differenziata resta sotto l'obiettivo e la regione paga ancora l'eredità dell'emergenza rifiuti (ecoballe, bonifiche). Nel 2025 la CEDU ha condannato l'Italia per la gestione della Terra dei Fuochi, imponendo un piano di risanamento: dossier ora sul tavolo della nuova giunta.",
      src:"ISPRA — Rapporto Rifiuti Urbani", url:"https://www.isprambiente.gov.it/it/istituto-informa/comunicati-stampa/anno-2024/rifiuti-urbani-nel-2023-cresce-dello-0-7-la-produzione", asof:"2022" },
    { area:"Trasporti", title:"Rifondare il trasporto pubblico (EAV e Circumvesuviana)",
      promise:"Promessa simbolo di Fico in campagna elettorale: treni dignitosi sulla Circumvesuviana, la linea più criticata d'Italia nei rapporti Pendolaria.",
      cur:"critico", curLbl:"servizio EAV: guasti e soppressioni ricorrenti", base:"Circumvesuviana maglia nera nei rapporti Pendolaria",
      delta:"nuovi treni in arrivo", deltaCls:"up-good", deltaSub:"consegne graduali in corso", barPct:25, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"La Circumvesuviana resta tra le peggiori linee d'Italia per età dei treni, guasti e soppressioni (Pendolaria, Legambiente). Le prime consegne dei nuovi convogli EAV sono iniziate, ma il rinnovo completo della flotta richiederà anni: qui si misurerà la promessa della legislatura.",
      src:"Legambiente — Rapporto Pendolaria", url:"https://pendolaria.legambiente.it/", asof:"2025" },
    { area:"Giovani e reddito", title:"Trattenere i giovani in Campania",
      promise:"Il programma Fico propone misure regionali di sostegno a formazione e autonomia dei giovani per frenare l'emigrazione verso Nord ed estero.",
      cur:"saldo negativo", curLbl:"migrazione netta dei giovani verso altre regioni", base:"decine di migliaia di trasferimenti l'anno dal Mezzogiorno",
      delta:"misure appena varate", deltaCls:"up-good", deltaSub:"effetti non ancora misurabili", barPct:20, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"La Campania è tra le prime regioni per emigrazione giovanile qualificata (rapporti SVIMEZ e ISTAT sulle migrazioni interne). Le misure della nuova giunta sono in fase di avvio: l'indicatore da osservare nei prossimi anni è il saldo migratorio dei 18-34enni.",
      src:"SVIMEZ / ISTAT — Migrazioni interne", url:"https://www.svimez.it/", asof:"2024" }
  ]
};
