window.DASH = window.DASH || {};
window.DASH.emiliaromagna = {
  meta: {
    nome: "Emilia-Romagna",
    area: "Nord",
    presidente: "Michele de Pascale",
    maggioranza: "centrosinistra",
    stemma: "🏰"
  },
  ui: {
    h1: "Emilia-Romagna — Programma vs Realtà",
    sub: "Monitoraggio di 6 indicatori (4 comuni + 2 specifici) del programma della giunta de Pascale, in carica da dicembre 2024.",
    metaHtml: "Dati aggiornati a <b>luglio 2026</b> · Fonti: Ministero della Salute, ISTAT, ISPRA, Ministero dell'Interno · <b>Il valore (KPI) è misurato; lo «stato» è una valutazione. Correlazione ≠ causalità.</b>",
    searchPlaceholder: "Cerca indicatore…",
    chipsAll: "Tutte le aree",
    hint: "Clicca una scheda per aprire dettaglio, nota e fonte.",
    emptyMsg: "Nessun indicatore corrisponde ai filtri.",
    startLabel: "Punto di partenza",
    noteLabel: "Nota",
    sourceLabel: "Fonte",
    footerHtml: "<p><b>Metodologia.</b> Quattro stati: <span style='color:var(--green)'>In linea</span> (obiettivo raggiunto), <span style='color:var(--blue)'>In corso</span> (progressi coerenti con l'impegno), <span style='color:var(--amber)'>In ritardo</span> (progressi insufficienti), <span style='color:var(--red)'>Fermo</span> (nessun progresso misurabile). Gli indicatori misurano il contesto regionale: l'andamento non è attribuibile per intero all'azione della giunta (correlazione ≠ causalità). Dove indicato, i valori sono stime; i dati mancanti sono dichiarati.</p>"
  },
  status: {
    "in-linea": { label: "In linea",  cls: "s-green" },
    "in-corso": { label: "In corso",  cls: "s-blue"  },
    "ritardo":  { label: "In ritardo", cls: "s-amber" },
    "fermo":    { label: "Fermo",     cls: "s-red"   }
  },
  items: [
    { area:"Sanità", title:"Difendere la sanità pubblica universalistica",
      promise:"Primo punto del programma de Pascale: rilanciare la sanità pubblica, ridurre le attese e chiedere più risorse al governo per il fondo sanitario.",
      cur:"3/3", curLbl:"macro-aree LEA sopra la soglia di sufficienza (2023)", base:"Regione storicamente ai vertici del monitoraggio",
      delta:"adempiente", deltaCls:"up-good", deltaSub:"tra i punteggi più alti", barPct:85, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"L'Emilia-Romagna è sufficiente in tutte le macro-aree LEA 2023 con punteggi ai vertici nazionali. Il bilancio sanitario regionale è però in tensione: la giunta ha introdotto misure fiscali per coprire il disavanzo della sanità.",
      src:"Ministero della Salute — Nuovo Sistema di Garanzia", url:"https://www.salute.gov.it/new/it/news-e-media/notizie/livelli-essenziali-di-assistenza-sintesi-dei-risultati-del-nuovo-sistema-di/", asof:"2023 (relazione 2025)" },
    { area:"Sicurezza", title:"Sicurezza urbana lungo la via Emilia",
      promise:"Impegni su sicurezza integrata, polizia locale e prevenzione nelle città della via Emilia e in Riviera.",
      cur:"≈4.400", curLbl:"delitti denunciati ogni 100.000 abitanti (2022)", base:"media Italia: ≈3.800 ogni 100.000",
      delta:"+16% vs Italia", deltaCls:"up-bad", deltaSub:"Bologna e Rimini tra le prime province", barPct:45, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"L'Emilia-Romagna è tra le prime regioni per denunce in rapporto alla popolazione; Bologna e Rimini figurano stabilmente ai vertici dell'Indice della criminalità del Sole 24 Ore. Il dato risente anche della maggiore propensione alla denuncia. Valore arrotondato, dati 2022.",
      src:"ISTAT / Il Sole 24 Ore — Indice della criminalità", url:"https://lab24.ilsole24ore.com/indice-della-criminalita/", asof:"2022" },
    { area:"Lavoro", title:"Lavoro di qualità e salari",
      promise:"Il programma promette un patto per il lavoro e per il clima aggiornato, con focus su salari e stabilità dei contratti.",
      cur:"70,4%", curLbl:"tasso di occupazione 15-64 anni (2023, arrotondato)", base:"media Italia: 61,5% (2023)",
      delta:"+8,9 pt vs Italia", deltaCls:"up-good", deltaSub:"seconda regione d'Italia", barPct:70, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Tasso di occupazione tra i più alti d'Italia, sopra il 70%. Le vertenze aperte (automotive, moda) e la qualità dei contratti restano i fronti su cui si misura la promessa di «lavoro di qualità». Valore arrotondato.",
      src:"ISTAT — Rilevazione sulle forze di lavoro", url:"https://noi-italia.istat.it/pagina.php?id=3&categoria=16&action=show&L=0", asof:"2023" },
    { area:"Ambiente", title:"Seconda regione per raccolta differenziata",
      promise:"Continuità del patto per il clima: economia circolare e riduzione del consumo di suolo.",
      cur:"77,1%", curLbl:"raccolta differenziata (2023)", base:"obiettivo di legge: 65%",
      delta:"+12,1 pt vs obiettivo", deltaCls:"up-good", deltaSub:"seconda regione d'Italia", barPct:77, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Con il 77,1% nel 2023 la regione è seconda in Italia per raccolta differenziata (Reggio Emilia prima provincia con 83,3%). Il consumo di suolo, tra i più alti del Paese, resta il punto debole segnalato da ISPRA.",
      src:"ISPRA — Rapporto Rifiuti Urbani 2024", url:"https://ambiente.regione.emilia-romagna.it/it/notizie/attualita/2024/dicembre/rapporto-annuale-ispra-sui-rifiuti-urbani-lemilia-romagna-scala-due-posizioni-ed-e-seconda-in-italia-per-raccolta-differenziata", asof:"2023" },
    { area:"Ricostruzione", title:"Ricostruzione post-alluvione e difesa del suolo",
      promise:"Impegno centrale del programma dopo le alluvioni del 2023-2024: ristori rapidi ai cittadini e piano straordinario di sicurezza idraulica.",
      cur:"parziale", curLbl:"avanzamento di ristori e opere di difesa idraulica", base:"alluvioni di maggio 2023 e settembre-ottobre 2024",
      delta:"ritmi contestati", deltaCls:"up-bad", deltaSub:"rimborsi più lenti delle attese", barPct:40, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"La ricostruzione procede tra gestione commissariale nazionale e Regione: una percentuale ufficiale unica di ristori erogati non è disponibile in forma consolidata, ma comitati e stampa documentano tempi più lenti delle promesse. Le opere di laminazione richiedono anni di cantieri.",
      src:"Struttura commissariale ricostruzione post-alluvione", url:"https://commissari.gov.it/alluvione-centro-nord-2023/", asof:"2025" },
    { area:"Casa", title:"Piano casa per studenti e lavoratori",
      promise:"Il programma de Pascale promette un piano casa regionale: affitti calmierati e recupero del patrimonio ERP sfitto.",
      cur:"avviato", curLbl:"piano casa regionale approvato, prime risorse stanziate", base:"emergenza affitti a Bologna e in Riviera a inizio mandato",
      delta:"prime misure", deltaCls:"up-good", deltaSub:"effetti ancora da misurare", barPct:35, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"La giunta ha varato le prime misure sull'abitare (fondi per l'ERP e per l'affitto), ma l'impatto su canoni e disponibilità di alloggi non è ancora misurabile: il numero di alloggi effettivamente recuperati o convenzionati a oggi non è disponibile in forma consolidata.",
      src:"Regione Emilia-Romagna — Politiche abitative", url:"https://territorio.regione.emilia-romagna.it/politiche-abitative", asof:"2025" }
  ]
};
