window.DASH = window.DASH || {};
window.DASH.friuliveneziagiulia = {
  meta: {
    nome: "Friuli-Venezia Giulia",
    area: "Nord",
    presidente: "Massimiliano Fedriga",
    maggioranza: "centrodestra",
    stemma: "🦅"
  },
  ui: {
    h1: "Friuli-Venezia Giulia — Programma vs Realtà",
    sub: "Monitoraggio di 6 indicatori (4 comuni + 2 specifici) del programma della giunta Fedriga II, in carica da aprile 2023.",
    metaHtml: "Dati aggiornati a <b>luglio 2026</b> · Fonti: Ministero della Salute, ISTAT, ISPRA, Ministero dell'Interno · <b>Il valore (KPI) è misurato; lo «stato» è una valutazione. Correlazione ≠ causalità.</b>",
    searchPlaceholder: "Cerca indicatore…",
    chipsAll: "Tutte le aree",
    hint: "Clicca una scheda per aprire dettaglio, nota e fonte.",
    emptyMsg: "Nessun indicatore corrisponde ai filtri.",
    startLabel: "Punto di partenza",
    noteLabel: "Nota",
    sourceLabel: "Fonte",
    footerHtml: "<p><b>Metodologia.</b> Quattro stati: <span style='color:var(--green)'>In linea</span> (obiettivo raggiunto), <span style='color:var(--blue)'>In corso</span> (progressi coerenti con l'impegno), <span style='color:var(--amber)'>In ritardo</span> (progressi insufficienti), <span style='color:var(--red)'>Fermo</span> (nessun progresso misurabile). Gli indicatori misurano il contesto regionale: l'andamento non è attribuibile per intero all'azione della giunta (correlazione ≠ causalità). Dove indicato, i valori sono stime; i dati mancanti sono dichiarati.</p>"
  },
  status: {
    "in-linea": { label: "In linea",  cls: "s-green" },
    "in-corso": { label: "In corso",  cls: "s-blue"  },
    "ritardo":  { label: "In ritardo", cls: "s-amber" },
    "fermo":    { label: "Fermo",     cls: "s-red"   }
  },
  items: [
    { area:"Sanità", title:"LEA garantiti e attese in riduzione",
      promise:"Il programma Fedriga II promette il rafforzamento della sanità territoriale e il recupero delle liste d'attesa post-Covid.",
      cur:"3/3", curLbl:"macro-aree LEA sopra la soglia di sufficienza (2023)", base:"Regione adempiente anche nel 2022",
      delta:"adempiente", deltaCls:"up-good", deltaSub:"Nuovo Sistema di Garanzia", barPct:78, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Il FVG supera la soglia in tutte e tre le macro-aree del monitoraggio LEA 2023. La carenza di medici e infermieri, comune a tutto il Nord-Est, resta la criticità principale segnalata dai sindacati di categoria.",
      src:"Ministero della Salute — Nuovo Sistema di Garanzia", url:"https://www.salute.gov.it/new/it/news-e-media/notizie/livelli-essenziali-di-assistenza-sintesi-dei-risultati-del-nuovo-sistema-di/", asof:"2023 (relazione 2025)" },
    { area:"Sicurezza", title:"Tra le regioni con meno reati",
      promise:"Impegni su sicurezza urbana a Trieste e Udine e gestione della rotta balcanica.",
      cur:"≈2.800", curLbl:"delitti denunciati ogni 100.000 abitanti (2022)", base:"media Italia: ≈3.800 ogni 100.000",
      delta:"-26% vs Italia", deltaCls:"up-good", deltaSub:"tra le più sicure d'Italia", barPct:80, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Il FVG è tra le regioni con meno denunce in rapporto alla popolazione (circa 2,8 ogni 100 abitanti nel 2022). Il tema politicamente più discusso è la gestione dei flussi migratori lungo la rotta balcanica a Trieste.",
      src:"ISTAT — Delitti denunciati (elab. Pagella Politica)", url:"https://pagellapolitica.it/articoli/mappe-denunce-reati-forze-ordine-italia", asof:"2022" },
    { area:"Lavoro", title:"Occupazione alta, demografia debole",
      promise:"Il programma punta su attrazione di investimenti, lavoro qualificato e politiche per la natalità.",
      cur:"67,9%", curLbl:"tasso di occupazione 15-64 anni (2023, arrotondato)", base:"media Italia: 61,5% (2023)",
      delta:"+6,4 pt vs Italia", deltaCls:"up-good", deltaSub:"sopra la media nazionale", barPct:68, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Occupazione sopra la media, con domanda di lavoro superiore all'offerta in molti settori. Il declino demografico è il principale freno: la regione perde popolazione in età da lavoro. Valore arrotondato: verificare su dati.istat.it.",
      src:"ISTAT — Rilevazione sulle forze di lavoro", url:"https://noi-italia.istat.it/pagina.php?id=3&categoria=16&action=show&L=0", asof:"2023" },
    { area:"Ambiente", title:"Differenziata oltre il 65%",
      promise:"Impegni su economia circolare e transizione energetica delle imprese.",
      cur:"67,5%", curLbl:"raccolta differenziata (2022)", base:"obiettivo di legge: 65%",
      delta:"+2,5 pt vs obiettivo", deltaCls:"up-good", deltaSub:"sopra la soglia di legge", barPct:68, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Obiettivo di legge superato. Restano i dossier ambientali industriali (area di Trieste, Ferriera dismessa) e la decarbonizzazione del sistema portuale.",
      src:"ISPRA — Rapporto Rifiuti Urbani", url:"https://www.isprambiente.gov.it/it/istituto-informa/comunicati-stampa/anno-2024/rifiuti-urbani-nel-2023-cresce-dello-0-7-la-produzione", asof:"2022" },
    { area:"Porto e logistica", title:"Trieste hub logistico europeo",
      promise:"Il programma indica porto di Trieste, interporti e ferrovie come motore di sviluppo della regione.",
      cur:"≈62 mln t", curLbl:"merci movimentate dal porto di Trieste in un anno (stima)", base:"primo porto italiano per tonnellaggio",
      delta:"primato confermato", deltaCls:"up-good", deltaSub:"traffico ferroviario in crescita", barPct:75, barCol:"var(--green)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Trieste resta il primo porto italiano per tonnellaggio complessivo, con forte crescita dell'intermodale ferroviario verso l'Europa centrale. Valore stimato: i consuntivi annuali sono pubblicati dall'Autorità di Sistema Portuale del Mare Adriatico Orientale.",
      src:"Autorità di Sistema Portuale del Mare Adriatico Orientale", url:"https://www.porto.trieste.it/", asof:"2024 (stima)" },
    { area:"Famiglia e natalità", title:"Invertire il declino demografico",
      promise:"Pacchetto famiglia della giunta: contributi per i nuovi nati, asili e casa per le giovani coppie.",
      cur:"in calo", curLbl:"nascite annue in regione, trend negativo", base:"saldo naturale negativo da oltre un decennio",
      delta:"trend nazionale", deltaCls:"up-bad", deltaSub:"natalità ai minimi storici", barPct:25, barCol:"var(--red)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Nonostante le misure regionali (dote famiglia, contributi prima casa), le nascite continuano a diminuire in linea col trend nazionale: il numero esatto per l'ultimo anno è disponibile su demo.istat.it. Invertire una tendenza demografica richiede tempi lunghi, ben oltre una legislatura.",
      src:"ISTAT — Indicatori demografici", url:"https://demo.istat.it/", asof:"2024" }
  ]
};
