window.DASH = window.DASH || {};
window.DASH.governo = {
  meta: {
    nome: "Governo Italiano",
    area: "Nazionale",
    presidente: "Giorgia Meloni",
    maggioranza: "centrodestra (FdI, Lega, Forza Italia, Noi Moderati)",
    stemma: "🇮🇹"
  },
  ui: {
    h1: "Governo Italiano — Programma vs Realtà",
    sub: "Monitoraggio di 12 indicatori nazionali del programma del Governo Meloni, in carica da ottobre 2022.",
    metaHtml: "Dati aggiornati a <b>luglio 2026</b> · Fonti: ISTAT, Banca d'Italia, MEF, Ministero dell'Interno, Terna, GIMBE · <b>Il valore (KPI) è misurato; lo «stato» è una valutazione. Correlazione ≠ causalità.</b>",
    searchPlaceholder: "Cerca indicatore…",
    chipsAll: "Tutte le aree",
    hint: "Clicca una scheda per aprire dettaglio, nota e fonte.",
    emptyMsg: "Nessun indicatore corrisponde ai filtri.",
    startLabel: "Punto di partenza",
    noteLabel: "Nota",
    sourceLabel: "Fonte",
    footerHtml: "<p><b>Metodologia.</b> Quattro stati: <span style='color:var(--green)'>In linea</span> (obiettivo raggiunto), <span style='color:var(--blue)'>In corso</span> (progressi coerenti con l'impegno), <span style='color:var(--amber)'>In ritardo</span> (progressi insufficienti), <span style='color:var(--red)'>Fermo</span> (nessun progresso misurabile). Gli indicatori misurano il contesto nazionale: l'andamento non è attribuibile per intero all'azione del governo (correlazione ≠ causalità). Dove indicato, i valori sono stime o dati provvisori; i dati mancanti sono dichiarati.</p>"
  },
  status: {
    "in-linea": { label: "In linea",  cls: "s-green" },
    "in-corso": { label: "In corso",  cls: "s-blue"  },
    "ritardo":  { label: "In ritardo", cls: "s-amber" },
    "fermo":    { label: "Fermo",     cls: "s-red"   }
  },
  items: [
    { area:"Economia", title:"Rilanciare la crescita del PIL",
      promise:"Il programma di centrodestra punta a una crescita economica stabile e superiore alla media UE, trainata da investimenti e domanda interna.",
      cur:"+0,5%", curLbl:"crescita del PIL in volume (2025)", base:"+0,7% nel 2024",
      delta:"in rallentamento", deltaCls:"up-bad", deltaSub:"sotto la media dell'eurozona", barPct:35, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Nel 2025 il PIL cresce dello 0,5% (2.258 miliardi a prezzi correnti), in decelerazione rispetto al 2024 e sotto le previsioni del governo. Il traino resta la domanda interna e gli investimenti PNRR. Dato ISTAT provvisorio.",
      src:"ISTAT — Conti economici nazionali", url:"https://www.istat.it/it/archivio/conti+nazionali", asof:"2025 (marzo 2026)" },

    { area:"Conti pubblici", title:"Tenere sotto controllo il debito pubblico",
      promise:"Impegno a mantenere i conti in ordine e ad avviare la riduzione del rapporto debito/PIL.",
      cur:"137,1%", curLbl:"debito pubblico in rapporto al PIL (2025)", base:"134,7% nel 2024",
      delta:"+2,4 pt", deltaCls:"up-bad", deltaSub:"debito ancora in salita", barPct:22, barCol:"var(--red)",
      status:"fermo", badge:"Fermo", bCls:"b-red",
      note:"Il rapporto debito/PIL sale al 137,1% dal 134,7% del 2024, in parte per la coda degli incentivi edilizi (Superbonus). La discesa promessa non è ancora iniziata. Dato ISTAT/Banca d'Italia.",
      src:"Banca d'Italia — Finanza pubblica", url:"https://www.bancaditalia.it/pubblicazioni/finanza-pubblica/", asof:"2025" },

    { area:"Conti pubblici", title:"Riportare il deficit sotto il 3%",
      promise:"Uscire dalla procedura per deficit eccessivo della UE riducendo l'indebitamento netto verso la soglia del 3%.",
      cur:"3,1%", curLbl:"deficit in rapporto al PIL (2025)", base:"3,4% nel 2024 (7,2% nel 2023)",
      delta:"-0,3 pt", deltaCls:"up-good", deltaSub:"vicino all'obiettivo del 3%", barPct:70, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Il deficit scende al 3,1% dal 3,4% del 2024 e dal 7,2% del 2023 (drogato dal Superbonus): il rientro sotto il 3% è ormai a portata. Dato provvisorio, soggetto a revisione fino alla notifica di aprile.",
      src:"ISTAT — Notifica indebitamento AP", url:"https://www.istat.it/it/archivio/conti+nazionali", asof:"2025 (provvisorio)" },

    { area:"Mercati", title:"Mantenere la fiducia dei mercati (spread)",
      promise:"Preservare la credibilità finanziaria del Paese e contenere il costo del debito.",
      cur:"≈83 pb", curLbl:"spread BTP-Bund a 10 anni (luglio 2026)", base:"≈240 pb a ottobre 2022",
      delta:"-65% dal 2022", deltaCls:"up-good", deltaSub:"ma in risalita da giugno", barPct:80, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Lo spread è sceso stabilmente sotto i 100 punti base, molto lontano dai picchi del 2022. A luglio 2026 risale verso 83 pb con rendimenti attorno al 4%, per tensioni geopolitiche internazionali. Fonte: mercati.",
      src:"Il Sole 24 Ore — Spread BTP-Bund", url:"https://mercati.ilsole24ore.com/obbligazioni/spread/btp-10a-bund-10a", asof:"luglio 2026" },

    { area:"Lavoro", title:"Aumentare l'occupazione",
      promise:"Il governo rivendica un mercato del lavoro più forte con nuovi posti e più contratti stabili.",
      cur:"62,7%", curLbl:"tasso di occupazione 15-64 anni (record storico, 2025)", base:"≈60,1% nel 2022",
      delta:"+2,6 pt", deltaCls:"up-good", deltaSub:"massimo dal 2004", barPct:85, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"A ottobre 2025 il tasso di occupazione tocca il 62,7%, record da quando esistono le rilevazioni ISTAT (2004), con oltre 24,2 milioni di occupati e crescita dei contratti a tempo indeterminato. Resta il divario di genere e territoriale.",
      src:"ISTAT — Occupati e disoccupati", url:"https://www.istat.it/comunicato-stampa/occupati-e-disoccupati-dati-provvisori-dicembre-2025/", asof:"2025" },

    { area:"Lavoro", title:"Ridurre la disoccupazione giovanile",
      promise:"Favorire l'ingresso dei giovani nel mercato del lavoro e ridurre i NEET.",
      cur:"≈20,5%", curLbl:"disoccupazione 15-24 anni (dicembre 2025)", base:"≈23,7% nel 2022",
      delta:"in miglioramento", deltaCls:"up-good", deltaSub:"ma ancora una su cinque", barPct:45, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"La disoccupazione giovanile scende rispetto al 2022 ma resta strutturalmente alta (oltre il 20%) e volatile mese su mese: a fine 2025 risale di 1,4 punti. Il nodo NEET e il divario Nord-Sud restano aperti.",
      src:"ISTAT — Occupati e disoccupati", url:"https://www.istat.it/comunicato-stampa/occupati-e-disoccupati-dati-provvisori-dicembre-2025/", asof:"dicembre 2025" },

    { area:"Prezzi", title:"Difendere il potere d'acquisto (inflazione)",
      promise:"Riportare l'inflazione su livelli fisiologici dopo lo shock energetico del 2022.",
      cur:"+1,5%", curLbl:"inflazione media annua (2025)", base:"+8,1% nel 2022 (+5,7% nel 2023)",
      delta:"rientrata", deltaCls:"up-good", deltaSub:"vicino al target BCE del 2%", barPct:82, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"L'inflazione media 2025 è all'1,5% (da 1,0% del 2024), ben lontana dai picchi del 2022-2023. Pesano ancora gli energetici regolamentati (+16,2%) e gli alimentari freschi (+3,4%); l'inflazione di fondo è all'1,9%.",
      src:"ISTAT — Prezzi al consumo", url:"https://www.istat.it/it/archivio/prezzi", asof:"media 2025" },

    { area:"Immigrazione", title:"Ridurre gli sbarchi irregolari",
      promise:"Tema bandiera del governo: contrastare l'immigrazione irregolare e gli arrivi via mare (Piano Mattei, accordi con la Libia e la Tunisia, protocollo Albania).",
      cur:"66.296", curLbl:"sbarchi via mare (2025)", base:"157.651 nel 2023",
      delta:"-58% dal 2023", deltaCls:"up-good", deltaSub:"stabile sul 2024 (-0,48%)", barPct:78, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Gli sbarchi 2025 (66.296) sono in forte calo rispetto al picco del 2023, ma quasi invariati sul 2024. In aumento gli arrivi dalla Libia (+38%). I rimpatri effettivi restano limitati e il protocollo Albania è stato oggetto di contenziosi: obiettivo dichiarato raggiunto sui numeri, non sull'intero impianto.",
      src:"Ministero dell'Interno — Cruscotto statistico", url:"https://www.interno.gov.it/it/stampa-e-comunicazione/dati-e-statistiche/sbarchi-e-accoglienza-dei-migranti-tutti-i-dati", asof:"31 dicembre 2025" },

    { area:"PNRR", title:"Attuare il PNRR nei tempi",
      promise:"Realizzare gli obiettivi del Piano Nazionale di Ripresa e Resilienza e incassare tutte le rate europee.",
      cur:"9/10 rate", curLbl:"rate incassate · ≈166 mld richiesti (2026)", base:"avvio del Piano nel 2021",
      delta:"tutti i 416 obiettivi", deltaCls:"up-good", deltaSub:"Italia capofila UE", barPct:80, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"A maggio 2026 l'Italia ha raggiunto tutti i 416 obiettivi programmati e incassato 9 rate su 10 (≈79% della dotazione). Resta la sfida della spesa effettiva (113,5 mld a febbraio 2026) e dell'ultimo miglio entro la scadenza di agosto 2026.",
      src:"Governo Italiano — Italia Domani (PNRR)", url:"https://www.governo.it/it/approfondimento/pnrr/16608", asof:"maggio 2026" },

    { area:"Fisco", title:"Abbassare le tasse (cuneo e pressione fiscale)",
      promise:"Il programma promette meno tasse su lavoro e imprese: taglio del cuneo fiscale, riforma IRPEF, flat tax incrementale.",
      cur:"43,1%", curLbl:"pressione fiscale in rapporto al PIL (2025)", base:"42,4% nel 2024",
      delta:"+0,7 pt", deltaCls:"up-bad", deltaSub:"record dal 2014", barPct:30, barCol:"var(--red)",
      status:"fermo", badge:"Fermo", bCls:"b-red",
      note:"Nonostante il taglio del cuneo fiscale e la riduzione degli scaglioni IRPEF, la pressione fiscale complessiva sale al 43,1%, il massimo dal 2014. Il fiscal drag (inflazione che spinge i redditi verso aliquote più alte) ha eroso i benefici: la promessa di meno tasse resta disattesa sul dato aggregato.",
      src:"ISTAT — Conti trimestrali PA", url:"https://www.istat.it/it/archivio/conti+nazionali", asof:"2025" },

    { area:"Sanità", title:"Rafforzare il Servizio Sanitario Nazionale",
      promise:"Ridurre le liste d'attesa e aumentare le risorse per la sanità pubblica.",
      cur:"6,4%", curLbl:"spesa sanitaria pubblica in rapporto al PIL (2025)", base:"6,3% nel 2024",
      delta:"+0,1 pt", deltaCls:"up-good", deltaSub:"sotto la media UE", barPct:48, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"La spesa sanitaria pubblica sale in valore assoluto ma resta ferma al 6,4% del PIL, sotto la media UE; secondo GIMBE il SSN è ancora sottofinanziato. Le prestazioni garantite nei tempi migliorano (86,5% nel 2024), ma il vincolo sulle assunzioni di personale frena la legge sulle liste d'attesa.",
      src:"GIMBE / Ministero della Salute", url:"https://www.gimbe.org/osservatorio/", asof:"2025" },

    { area:"Ambiente", title:"Accelerare sulle rinnovabili",
      promise:"Aumentare la quota di energia da fonti rinnovabili verso gli obiettivi europei al 2030 (65% dei consumi elettrici).",
      cur:"41%", curLbl:"quota rinnovabili sui consumi elettrici (2025)", base:"obiettivo 2030: 65%",
      delta:"-1 pt sul 2024", deltaCls:"up-bad", deltaSub:"crescita di capacità, produzione idro in calo", barPct:63, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Nel 2025 le rinnovabili coprono il 41% dei consumi elettrici (311,3 TWh totali), in lieve calo sul 2024 per la minore idroelettricità, nonostante il fotovoltaico a +25,1%. La capacità installata cresce ma il ritmo va accelerato per centrare il target 2030.",
      src:"Terna — Sistema elettrico", url:"https://www.terna.it/it/sistema-elettrico/dispacciamento/dati-esercizio", asof:"2025" }
  ]
};
