window.DASH = window.DASH || {};
window.DASH.lazio = {
  meta: {
    nome: "Lazio",
    area: "Centro",
    presidente: "Francesco Rocca",
    maggioranza: "centrodestra",
    stemma: "🐺"
  },
  ui: {
    h1: "Lazio — Programma vs Realtà",
    sub: "Monitoraggio di 6 indicatori (4 comuni + 2 specifici) del programma della giunta Rocca, in carica da marzo 2023.",
    metaHtml: "Dati aggiornati a <b>luglio 2026</b> · Fonti: Ministero della Salute, ISTAT, ISPRA, Ministero dell'Interno · <b>Il valore (KPI) è misurato; lo «stato» è una valutazione. Correlazione ≠ causalità.</b>",
    searchPlaceholder: "Cerca indicatore…",
    chipsAll: "Tutte le aree",
    hint: "Clicca una scheda per aprire dettaglio, nota e fonte.",
    emptyMsg: "Nessun indicatore corrisponde ai filtri.",
    startLabel: "Punto di partenza",
    noteLabel: "Nota",
    sourceLabel: "Fonte",
    footerHtml: "<p><b>Metodologia.</b> Quattro stati: <span style='color:var(--green)'>In linea</span> (obiettivo raggiunto), <span style='color:var(--blue)'>In corso</span> (progressi coerenti con l'impegno), <span style='color:var(--amber)'>In ritardo</span> (progressi insufficienti), <span style='color:var(--red)'>Fermo</span> (nessun progresso misurabile). Gli indicatori misurano il contesto regionale: l'andamento non è attribuibile per intero all'azione della giunta (correlazione ≠ causalità). Dove indicato, i valori sono stime; i dati mancanti sono dichiarati.</p>"
  },
  status: {
    "in-linea": { label: "In linea",  cls: "s-green" },
    "in-corso": { label: "In corso",  cls: "s-blue"  },
    "ritardo":  { label: "In ritardo", cls: "s-amber" },
    "fermo":    { label: "Fermo",     cls: "s-red"   }
  },
  items: [
    { area:"Sanità", title:"Liste d'attesa: la promessa numero uno",
      promise:"Rocca (ex presidente della Croce Rossa) ha promesso di abbattere le liste d'attesa e riportare il Lazio fuori dal piano di rientro.",
      cur:"3/3", curLbl:"macro-aree LEA sopra la soglia di sufficienza (2023)", base:"Regione in piano di rientro dal 2007, uscita dal commissariamento nel 2020",
      delta:"adempiente", deltaCls:"up-good", deltaSub:"attese ancora critiche", barPct:70, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Il Lazio supera la soglia in tutte le macro-aree LEA 2023 e la giunta rivendica investimenti sulle liste d'attesa. Le associazioni dei pazienti continuano però a documentare attese lunghe per molte prestazioni; il bilancio sanitario resta sotto osservazione.",
      src:"Ministero della Salute — Nuovo Sistema di Garanzia", url:"https://www.salute.gov.it/new/it/news-e-media/notizie/livelli-essenziali-di-assistenza-sintesi-dei-risultati-del-nuovo-sistema-di/", asof:"2023 (relazione 2025)" },
    { area:"Sicurezza", title:"La regione con più denunce d'Italia",
      promise:"Impegni su sicurezza urbana, periferie di Roma e presidio del litorale.",
      cur:"≈4.800", curLbl:"delitti denunciati ogni 100.000 abitanti (2022)", base:"media Italia: ≈3.800 ogni 100.000",
      delta:"+26% vs Italia", deltaCls:"up-bad", deltaSub:"prima regione per denunce", barPct:30, barCol:"var(--red)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Il Lazio è la regione con più denunce in rapporto alla popolazione (4,8 ogni 100 abitanti nel 2022), trainato da Roma. Il dato risente della concentrazione metropolitana e turistica. Valore arrotondato su dati ISTAT.",
      src:"ISTAT — Delitti denunciati (elab. Pagella Politica)", url:"https://pagellapolitica.it/articoli/mappe-denunce-reati-forze-ordine-italia", asof:"2022" },
    { area:"Lavoro", title:"Occupazione poco sopra la media nazionale",
      promise:"Il programma punta su semplificazione, attrazione di investimenti (cinema, aerospazio, farmaceutica) e lavoro giovanile.",
      cur:"62,6%", curLbl:"tasso di occupazione 15-64 anni (2023, arrotondato)", base:"media Italia: 61,5% (2023)",
      delta:"+1,1 pt vs Italia", deltaCls:"up-good", deltaSub:"ultimo tra le regioni del Centro", barPct:63, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Nonostante il peso della capitale, il tasso di occupazione del Lazio è il più basso del Centro e appena sopra la media nazionale, con forti divari tra Roma e le province. Valore arrotondato: verificare su dati.istat.it.",
      src:"ISTAT — Rilevazione sulle forze di lavoro", url:"https://noi-italia.istat.it/pagina.php?id=3&categoria=16&action=show&L=0", asof:"2023" },
    { area:"Ambiente", title:"Differenziata lontana dall'obiettivo",
      promise:"Il programma promette l'autosufficienza impiantistica del ciclo dei rifiuti e il rilancio della differenziata.",
      cur:"54,5%", curLbl:"raccolta differenziata (2022)", base:"obiettivo di legge: 65%",
      delta:"-10,5 pt vs obiettivo", deltaCls:"up-bad", deltaSub:"terzultima in Italia", barPct:55, barCol:"var(--red)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Il Lazio resta tra le ultime regioni per raccolta differenziata, frenato da Roma. Gran parte dei rifiuti della capitale viene ancora trattata fuori regione, in attesa del termovalorizzatore promosso dal Comune di Roma (competenza non regionale).",
      src:"ISPRA — Rapporto Rifiuti Urbani", url:"https://www.isprambiente.gov.it/it/istituto-informa/comunicati-stampa/anno-2024/rifiuti-urbani-nel-2023-cresce-dello-0-7-la-produzione", asof:"2022" },
    { area:"Giubileo", title:"Gestire il Giubileo 2025 e la sua eredità",
      promise:"Il programma indica il Giubileo come occasione per sanità, trasporti e turismo: la Regione ha gestito il coordinamento sanitario e i flussi.",
      cur:">30 mln", curLbl:"pellegrini a Roma nell'anno giubilare (stima)", base:"evento concluso a gennaio 2026",
      delta:"evento gestito", deltaCls:"up-good", deltaSub:"senza criticità maggiori", barPct:80, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"L'anno giubilare si è chiuso con decine di milioni di pellegrini (le cifre ufficiali definitive sono state diffuse dal Dicastero vaticano e dalle strutture commissariali; il valore indicato è una stima di ordine di grandezza). La macchina sanitaria e dei trasporti ha retto senza emergenze rilevanti.",
      src:"Giubileo 2025 — struttura commissariale", url:"https://www.iubilaeum2025.va/", asof:"2025-2026 (stima)" },
    { area:"Trasporti", title:"Ferrovie regionali e nuove metropolitane",
      promise:"Impegni su ex Roma-Lido e Roma-Nord (passate ad ASTRAL/Cotral), rinnovo treni e collegamenti con le province.",
      cur:"parziale", curLbl:"rinnovo del materiale rotabile sulle ex concesse", base:"Roma-Lido tra le peggiori ferrovie d'Italia nei rapporti Pendolaria",
      delta:"primi nuovi treni", deltaCls:"up-good", deltaSub:"servizio ancora sotto standard", barPct:40, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Sulla Metromare (ex Roma-Lido) e sulla Roma-Civita Castellana-Viterbo sono arrivati nuovi treni e cantieri di ammodernamento, ma frequenze e affidabilità restano lontane dagli standard promessi: Pendolaria di Legambiente continua a segnalarle tra le linee peggiori d'Italia.",
      src:"Legambiente — Rapporto Pendolaria", url:"https://pendolaria.legambiente.it/", asof:"2025" }
  ]
};
