window.DASH = window.DASH || {};
window.DASH.liguria = {
  meta: {
    nome: "Liguria",
    area: "Nord",
    presidente: "Marco Bucci",
    maggioranza: "centrodestra",
    stemma: "⚓"
  },
  ui: {
    h1: "Liguria — Programma vs Realtà",
    sub: "Monitoraggio di 6 indicatori (4 comuni + 2 specifici) del programma della giunta Bucci, in carica da novembre 2024 dopo le dimissioni di Toti.",
    metaHtml: "Dati aggiornati a <b>luglio 2026</b> · Fonti: Ministero della Salute, ISTAT, ISPRA, Ministero dell'Interno · <b>Il valore (KPI) è misurato; lo «stato» è una valutazione. Correlazione ≠ causalità.</b>",
    searchPlaceholder: "Cerca indicatore…",
    chipsAll: "Tutte le aree",
    hint: "Clicca una scheda per aprire dettaglio, nota e fonte.",
    emptyMsg: "Nessun indicatore corrisponde ai filtri.",
    startLabel: "Punto di partenza",
    noteLabel: "Nota",
    sourceLabel: "Fonte",
    footerHtml: "<p><b>Metodologia.</b> Quattro stati: <span style='color:var(--green)'>In linea</span> (obiettivo raggiunto), <span style='color:var(--blue)'>In corso</span> (progressi coerenti con l'impegno), <span style='color:var(--amber)'>In ritardo</span> (progressi insufficienti), <span style='color:var(--red)'>Fermo</span> (nessun progresso misurabile). Gli indicatori misurano il contesto regionale: l'andamento non è attribuibile per intero all'azione della giunta (correlazione ≠ causalità). Dove indicato, i valori sono stime; i dati mancanti sono dichiarati.</p>"
  },
  status: {
    "in-linea": { label: "In linea",  cls: "s-green" },
    "in-corso": { label: "In corso",  cls: "s-blue"  },
    "ritardo":  { label: "In ritardo", cls: "s-amber" },
    "fermo":    { label: "Fermo",     cls: "s-red"   }
  },
  items: [
    { area:"Sanità", title:"Recuperare la sufficienza nella prevenzione",
      promise:"Priorità dichiarata di Bucci: liste d'attesa e riorganizzazione delle ASL, con la sanità come primo capitolo del programma.",
      cur:"2/3", curLbl:"macro-aree LEA sopra la soglia di sufficienza (2023)", base:"insufficienza nell'area prevenzione",
      delta:"1 area critica", deltaCls:"up-bad", deltaSub:"prevenzione sotto soglia", barPct:55, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Nel monitoraggio LEA 2023 la Liguria resta sotto la soglia di sufficienza nella macro-area della prevenzione (screening e coperture vaccinali). L'invecchiamento record della popolazione ligure pesa su tutto il sistema sanitario.",
      src:"Ministero della Salute — Nuovo Sistema di Garanzia", url:"https://www.salute.gov.it/new/it/news-e-media/notizie/livelli-essenziali-di-assistenza-sintesi-dei-risultati-del-nuovo-sistema-di/", asof:"2023 (relazione 2025)" },
    { area:"Sicurezza", title:"Ridurre i reati nei centri urbani",
      promise:"Impegni su sicurezza nei centri storici (Genova) e nelle stazioni.",
      cur:"≈4.300", curLbl:"delitti denunciati ogni 100.000 abitanti (2022)", base:"media Italia: ≈3.800 ogni 100.000",
      delta:"+13% vs Italia", deltaCls:"up-bad", deltaSub:"sopra la media nazionale", barPct:48, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"La Liguria è quarta tra le regioni per denunce in rapporto alla popolazione (4,3 ogni 100 abitanti nel 2022): pesa il carattere urbano e turistico del territorio. Valore arrotondato su dati ISTAT.",
      src:"ISTAT — Delitti denunciati (elab. Pagella Politica)", url:"https://pagellapolitica.it/articoli/mappe-denunce-reati-forze-ordine-italia", asof:"2022" },
    { area:"Lavoro", title:"Rilanciare l'occupazione in una regione anziana",
      promise:"Il programma punta su blue economy, portualità e alta tecnologia per creare lavoro qualificato.",
      cur:"64,7%", curLbl:"tasso di occupazione 15-64 anni (2023, arrotondato)", base:"media Italia: 61,5% (2023)",
      delta:"+3,2 pt vs Italia", deltaCls:"up-good", deltaSub:"ultima tra le regioni del Nord", barPct:65, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Occupazione sopra la media nazionale ma la più bassa del Nord. La demografia (età media più alta d'Italia) riduce la forza lavoro disponibile. Valore arrotondato: verificare su dati.istat.it.",
      src:"ISTAT — Rilevazione sulle forze di lavoro", url:"https://noi-italia.istat.it/pagina.php?id=3&categoria=16&action=show&L=0", asof:"2023" },
    { area:"Ambiente", title:"Differenziata sotto l'obiettivo di legge",
      promise:"Impegni su impiantistica per i rifiuti (la regione esporta gran parte dell'indifferenziato) e difesa del suolo.",
      cur:"57,5%", curLbl:"raccolta differenziata (2022)", base:"obiettivo di legge: 65%",
      delta:"-7,5 pt vs obiettivo", deltaCls:"up-bad", deltaSub:"peggiore del Nord", barPct:58, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"La Liguria è ultima nel Nord per raccolta differenziata e priva di impianti di chiusura del ciclo: l'indifferenziato viene in gran parte trattato fuori regione. Il dissesto idrogeologico resta l'altra emergenza ambientale strutturale.",
      src:"ISPRA — Rapporto Rifiuti Urbani", url:"https://www.isprambiente.gov.it/it/istituto-informa/comunicati-stampa/anno-2024/rifiuti-urbani-nel-2023-cresce-dello-0-7-la-produzione", asof:"2022" },
    { area:"Infrastrutture", title:"Terzo Valico e nodo di Genova",
      promise:"Bucci ha costruito la sua immagine sulle grandi opere: completare Terzo Valico, diga foranea e Gronda è il cuore del programma.",
      cur:"≈90%", curLbl:"avanzamento lavori Terzo Valico (stima)", base:"opera avviata nel 2012, completamento più volte rinviato",
      delta:"apertura rinviata", deltaCls:"up-bad", deltaSub:"orizzonte 2027", barPct:80, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Il Terzo Valico dei Giovi è in fase avanzata ma l'attivazione è slittata rispetto alle previsioni iniziali (orizzonte 2027). La nuova diga foranea di Genova è in costruzione con criticità tecniche e di costi documentate da ANAC e stampa. Percentuali indicate come stime.",
      src:"RFI / Commissario Terzo Valico", url:"https://www.rfi.it/", asof:"2025 (stima)" },
    { area:"Turismo", title:"Allungare la stagione turistica",
      promise:"Obiettivo del programma: destagionalizzare il turismo e gestire i flussi record delle Cinque Terre e di Portofino.",
      cur:"≈16 mln", curLbl:"presenze turistiche annue (stima)", base:"livelli pre-Covid superati",
      delta:"record post-Covid", deltaCls:"up-good", deltaSub:"pressione su borghi e sentieri", barPct:70, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Le presenze hanno superato i livelli pre-pandemia, con picchi di overtourism nei borghi costieri. Valore stimato dai bollettini dell'Osservatorio turistico regionale; il consuntivo definitivo va verificato sulle statistiche della Regione Liguria.",
      src:"Regione Liguria — Osservatorio turistico", url:"https://www.regione.liguria.it/", asof:"2024 (stima)" }
  ]
};
