window.DASH = window.DASH || {};
window.DASH.lombardia = {
  meta: {
    nome: "Lombardia",
    area: "Nord",
    presidente: "Attilio Fontana",
    maggioranza: "centrodestra",
    stemma: "🛡️"
  },
  ui: {
    h1: "Lombardia — Programma vs Realtà",
    sub: "Monitoraggio di 6 indicatori (4 comuni + 2 specifici) del programma della giunta Fontana II, in carica da marzo 2023.",
    metaHtml: "Dati aggiornati a <b>luglio 2026</b> · Fonti: Ministero della Salute, ISTAT, ISPRA, Ministero dell'Interno · <b>Il valore (KPI) è misurato; lo «stato» è una valutazione. Correlazione ≠ causalità.</b>",
    searchPlaceholder: "Cerca indicatore…",
    chipsAll: "Tutte le aree",
    hint: "Clicca una scheda per aprire dettaglio, nota e fonte.",
    emptyMsg: "Nessun indicatore corrisponde ai filtri.",
    startLabel: "Punto di partenza",
    noteLabel: "Nota",
    sourceLabel: "Fonte",
    footerHtml: "<p><b>Metodologia.</b> Quattro stati: <span style='color:var(--green)'>In linea</span> (obiettivo raggiunto), <span style='color:var(--blue)'>In corso</span> (progressi coerenti con l'impegno), <span style='color:var(--amber)'>In ritardo</span> (progressi insufficienti), <span style='color:var(--red)'>Fermo</span> (nessun progresso misurabile). Gli indicatori misurano il contesto regionale: l'andamento non è attribuibile per intero all'azione della giunta (correlazione ≠ causalità). Dove indicato, i valori sono stime o arrotondamenti; i dati mancanti sono dichiarati.</p>"
  },
  status: {
    "in-linea": { label: "In linea",  cls: "s-green" },
    "in-corso": { label: "In corso",  cls: "s-blue"  },
    "ritardo":  { label: "In ritardo", cls: "s-amber" },
    "fermo":    { label: "Fermo",     cls: "s-red"   }
  },
  items: [
    { area:"Sanità", title:"LEA garantiti e liste d'attesa sotto controllo",
      promise:"Il programma Fontana II promette il potenziamento della medicina territoriale (case di comunità) e la riduzione delle liste d'attesa.",
      cur:"3/3", curLbl:"macro-aree LEA sopra la soglia di sufficienza (2023)", base:"Regione storicamente adempiente",
      delta:"adempiente", deltaCls:"up-good", deltaSub:"tra i punteggi più alti", barPct:85, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"La Lombardia supera la soglia in tutte e tre le macro-aree del monitoraggio LEA 2023 con punteggi tra i migliori d'Italia. Le liste d'attesa e la fuga di personale verso il privato restano i punti più contestati dalle opposizioni.",
      src:"Ministero della Salute — Nuovo Sistema di Garanzia", url:"https://www.salute.gov.it/new/it/news-e-media/notizie/livelli-essenziali-di-assistenza-sintesi-dei-risultati-del-nuovo-sistema-di/", asof:"2023 (relazione 2025)" },
    { area:"Sicurezza", title:"Contrasto alla criminalità urbana",
      promise:"Più agenti di polizia locale, controllo di vicinato e sicurezza sulle metropolitane milanesi.",
      cur:"≈4.400", curLbl:"delitti denunciati ogni 100.000 abitanti (2022)", base:"media Italia: ≈3.800 ogni 100.000",
      delta:"+16% vs Italia", deltaCls:"up-bad", deltaSub:"Milano prima provincia per denunce", barPct:45, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"La Lombardia è seconda tra le regioni per denunce in rapporto alla popolazione e Milano è stabilmente prima tra le province (Indice della criminalità del Sole 24 Ore, edizioni 2024 e 2025). Valore arrotondato su dati ISTAT 2022.",
      src:"ISTAT / Il Sole 24 Ore — Indice della criminalità", url:"https://lab24.ilsole24ore.com/indice-della-criminalita/", asof:"2022" },
    { area:"Lavoro", title:"Restare la locomotiva occupazionale del Paese",
      promise:"Attrazione di investimenti, formazione tecnica (ITS) e sostegno alle imprese nel programma di mandato.",
      cur:"69,3%", curLbl:"tasso di occupazione 15-64 anni (2023)", base:"media Italia: 61,5% (2023)",
      delta:"+7,8 pt vs Italia", deltaCls:"up-good", deltaSub:"ben sopra la media", barPct:69, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Occupazione strutturalmente sopra la media nazionale, con un mercato del lavoro vicino al pieno impiego nelle province di Milano e Bergamo. Il costo degli alloggi a Milano è indicato dalle imprese come freno all'attrazione di lavoratori.",
      src:"ISTAT — Rilevazione sulle forze di lavoro", url:"https://noi-italia.istat.it/pagina.php?id=3&categoria=16&action=show&L=0", asof:"2023" },
    { area:"Ambiente", title:"Differenziata alta, aria da risanare",
      promise:"Impegni su economia circolare e qualità dell'aria nel bacino padano.",
      cur:"73,2%", curLbl:"raccolta differenziata (2022)", base:"obiettivo di legge: 65%",
      delta:"+8,2 pt vs obiettivo", deltaCls:"up-good", deltaSub:"sopra la soglia di legge", barPct:73, barCol:"var(--green)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Raccolta differenziata ampiamente sopra l'obiettivo. Lo stato resta «in corso» perché la qualità dell'aria è il vero nodo ambientale: la pianura lombarda registra superamenti ricorrenti dei limiti di PM10 ed è oggetto di infrazione UE.",
      src:"ISPRA — Rapporto Rifiuti Urbani", url:"https://www.isprambiente.gov.it/it/istituto-informa/comunicati-stampa/anno-2024/rifiuti-urbani-nel-2023-cresce-dello-0-7-la-produzione", asof:"2022" },
    { area:"Olimpiadi", title:"Milano-Cortina 2026: Giochi e legacy",
      promise:"Il programma di mandato indica le Olimpiadi invernali 2026 come volano di infrastrutture e turismo per tutta la regione.",
      cur:"Giochi svolti", curLbl:"Olimpiadi celebrate a febbraio 2026", base:"assegnazione 2019; opere in corso a inizio mandato",
      delta:"legacy in corso", deltaCls:"up-good", deltaSub:"opere post-Giochi da completare", barPct:70, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"I Giochi si sono svolti a febbraio 2026. Una parte delle opere di accompagnamento (soprattutto stradali e ferroviarie in Valtellina) era programmata con completamento anche dopo l'evento: una percentuale ufficiale consolidata di opere concluse non è disponibile.",
      src:"SIMICO — Società Infrastrutture Milano Cortina", url:"https://www.simico.it/", asof:"2026" },
    { area:"Trasporti", title:"Rinnovare la flotta dei treni regionali",
      promise:"Impegno su un servizio ferroviario regionale più affidabile, con il piano di 222 nuovi treni per Trenord.",
      cur:"in consegna", curLbl:"nuovi treni del piano da 222 convogli", base:"flotta tra le più vecchie del Nord a inizio piano (2017)",
      delta:"oltre metà", deltaCls:"up-good", deltaSub:"consegne stimate a fine 2025", barPct:60, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Il rinnovo della flotta Trenord procede (stima: oltre la metà dei 222 treni consegnata entro il 2025), ma puntualità e soppressioni restano oggetto di critiche ricorrenti dei pendolari. Il numero esatto di convogli in servizio a oggi non è disponibile in forma consolidata.",
      src:"Regione Lombardia / FNM — programma nuovi treni", url:"https://www.regione.lombardia.it/", asof:"2025 (stima)" }
  ]
};
