window.DASH = window.DASH || {};
window.DASH.marche = {
  meta: {
    nome: "Marche",
    area: "Centro",
    presidente: "Francesco Acquaroli",
    maggioranza: "centrodestra",
    stemma: "🦚"
  },
  ui: {
    h1: "Marche — Programma vs Realtà",
    sub: "Monitoraggio di 6 indicatori (4 comuni + 2 specifici) del programma della giunta Acquaroli II, riconfermata alle elezioni di settembre-ottobre 2025.",
    metaHtml: "Dati aggiornati a <b>luglio 2026</b> · Fonti: Ministero della Salute, ISTAT, ISPRA, Ministero dell'Interno · <b>Il valore (KPI) è misurato; lo «stato» è una valutazione. Correlazione ≠ causalità.</b>",
    searchPlaceholder: "Cerca indicatore…",
    chipsAll: "Tutte le aree",
    hint: "Clicca una scheda per aprire dettaglio, nota e fonte.",
    emptyMsg: "Nessun indicatore corrisponde ai filtri.",
    startLabel: "Punto di partenza",
    noteLabel: "Nota",
    sourceLabel: "Fonte",
    footerHtml: "<p><b>Metodologia.</b> Quattro stati: <span style='color:var(--green)'>In linea</span> (obiettivo raggiunto), <span style='color:var(--blue)'>In corso</span> (progressi coerenti con l'impegno), <span style='color:var(--amber)'>In ritardo</span> (progressi insufficienti), <span style='color:var(--red)'>Fermo</span> (nessun progresso misurabile). Gli indicatori misurano il contesto regionale: l'andamento non è attribuibile per intero all'azione della giunta (correlazione ≠ causalità). Dove indicato, i valori sono stime; i dati mancanti sono dichiarati.</p>"
  },
  status: {
    "in-linea": { label: "In linea",  cls: "s-green" },
    "in-corso": { label: "In corso",  cls: "s-blue"  },
    "ritardo":  { label: "In ritardo", cls: "s-amber" },
    "fermo":    { label: "Fermo",     cls: "s-red"   }
  },
  items: [
    { area:"Sanità", title:"LEA garantiti dopo la riforma delle AST",
      promise:"Il programma Acquaroli II rivendica la riforma sanitaria (aziende sanitarie territoriali) e promette liste d'attesa in calo.",
      cur:"3/3", curLbl:"macro-aree LEA sopra la soglia di sufficienza (2023)", base:"Regione adempiente anche nel 2022",
      delta:"adempiente", deltaCls:"up-good", deltaSub:"Nuovo Sistema di Garanzia", barPct:75, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Le Marche superano la soglia in tutte le macro-aree LEA 2023. La sanità è stata comunque il tema centrale della campagna 2025: mobilità passiva verso altre regioni e attese nelle aree interne restano criticità aperte.",
      src:"Ministero della Salute — Nuovo Sistema di Garanzia", url:"https://www.salute.gov.it/new/it/news-e-media/notizie/livelli-essenziali-di-assistenza-sintesi-dei-risultati-del-nuovo-sistema-di/", asof:"2023 (relazione 2025)" },
    { area:"Sicurezza", title:"Tra le regioni con meno denunce",
      promise:"Impegni su sicurezza urbana lungo la costa e contrasto alle baby gang.",
      cur:"≈2.700", curLbl:"delitti denunciati ogni 100.000 abitanti (2022)", base:"media Italia: ≈3.800 ogni 100.000",
      delta:"-29% vs Italia", deltaCls:"up-good", deltaSub:"tra le più sicure d'Italia", barPct:82, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Le Marche sono con il Molise la regione con meno denunce in rapporto alla popolazione (2,7 ogni 100 abitanti nel 2022). Valore arrotondato su dati ISTAT.",
      src:"ISTAT — Delitti denunciati (elab. Pagella Politica)", url:"https://pagellapolitica.it/articoli/mappe-denunce-reati-forze-ordine-italia", asof:"2022" },
    { area:"Lavoro", title:"Difendere il modello manifatturiero marchigiano",
      promise:"Il programma punta su distretti (calzature, mobile, meccanica), credito alle PMI e ZES per rilanciare la manifattura.",
      cur:"66,4%", curLbl:"tasso di occupazione 15-64 anni (2023, arrotondato)", base:"media Italia: 61,5% (2023)",
      delta:"+4,9 pt vs Italia", deltaCls:"up-good", deltaSub:"sopra la media nazionale", barPct:66, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Occupazione sopra la media, ma la crisi dei distretti calzaturieri (Fermano) e l'export in calo verso alcuni mercati pesano sulle prospettive. Valore arrotondato: verificare su dati.istat.it.",
      src:"ISTAT — Rilevazione sulle forze di lavoro", url:"https://noi-italia.istat.it/pagina.php?id=3&categoria=16&action=show&L=0", asof:"2023" },
    { area:"Ambiente", title:"Differenziata ben oltre il 65%",
      promise:"Impegni su economia circolare e difesa della costa dall'erosione.",
      cur:"72,0%", curLbl:"raccolta differenziata (2022)", base:"obiettivo di legge: 65%",
      delta:"+7,0 pt vs obiettivo", deltaCls:"up-good", deltaSub:"tra le migliori del Centro", barPct:72, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Raccolta differenziata ampiamente sopra l'obiettivo, ai vertici del Centro Italia. Erosione costiera e dissesto idrogeologico (alluvione del Misa 2022) restano i fronti ambientali più delicati.",
      src:"ISPRA — Rapporto Rifiuti Urbani", url:"https://www.isprambiente.gov.it/it/istituto-informa/comunicati-stampa/anno-2024/rifiuti-urbani-nel-2023-cresce-dello-0-7-la-produzione", asof:"2022" },
    { area:"Infrastrutture", title:"Uscire dall'isolamento infrastrutturale",
      promise:"Promessa storica di Acquaroli: completare la Fano-Grosseto, potenziare la SS16 e l'alta velocità adriatica.",
      cur:"parziale", curLbl:"avanzamento delle opere prioritarie regionali", base:"progetti pluridecennali incompiuti a inizio mandato",
      delta:"cantieri aperti", deltaCls:"up-good", deltaSub:"tempi lunghi", barPct:35, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Alcuni lotti (Quadrilatero, varianti SS16) sono avanzati, ma le opere simbolo — completamento Fano-Grosseto e velocizzazione della ferrovia adriatica — restano senza data certa di completamento: percentuali di avanzamento consolidate non disponibili.",
      src:"ANAS / RFI — opere nelle Marche", url:"https://www.stradeanas.it/", asof:"2025" },
    { area:"Turismo", title:"Le Marche come destinazione emergente",
      promise:"Il programma punta su promozione (Pesaro capitale della cultura 2024), borghi ed enoturismo per crescere nel turismo nazionale.",
      cur:"in crescita", curLbl:"presenze turistiche annue, massimi recenti", base:"≈10-11 mln di presenze annue (stima)",
      delta:"sopra il pre-Covid", deltaCls:"up-good", deltaSub:"forte stagionalità balneare", barPct:60, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Le presenze hanno recuperato e superato i livelli pre-pandemia, con l'effetto di Pesaro capitale italiana della cultura 2024. Valori stimati: i consuntivi sono pubblicati dall'Osservatorio regionale sul turismo.",
      src:"Regione Marche — Osservatorio turismo", url:"https://www.regione.marche.it/Regione-Utile/Turismo-Sport-Tempo-Libero", asof:"2024 (stima)" }
  ]
};
