window.DASH = window.DASH || {};
window.DASH.molise = {
  meta: {
    nome: "Molise",
    area: "Sud e Isole",
    presidente: "Francesco Roberti",
    maggioranza: "centrodestra",
    stemma: "⭐"
  },
  ui: {
    h1: "Molise — Programma vs Realtà",
    sub: "Monitoraggio di 6 indicatori (4 comuni + 2 specifici) del programma della giunta Roberti, in carica da luglio 2023.",
    metaHtml: "Dati aggiornati a <b>luglio 2026</b> · Fonti: Ministero della Salute, ISTAT, ISPRA, Ministero dell'Interno · <b>Il valore (KPI) è misurato; lo «stato» è una valutazione. Correlazione ≠ causalità.</b>",
    searchPlaceholder: "Cerca indicatore…",
    chipsAll: "Tutte le aree",
    hint: "Clicca una scheda per aprire dettaglio, nota e fonte.",
    emptyMsg: "Nessun indicatore corrisponde ai filtri.",
    startLabel: "Punto di partenza",
    noteLabel: "Nota",
    sourceLabel: "Fonte",
    footerHtml: "<p><b>Metodologia.</b> Quattro stati: <span style='color:var(--green)'>In linea</span> (obiettivo raggiunto), <span style='color:var(--blue)'>In corso</span> (progressi coerenti con l'impegno), <span style='color:var(--amber)'>In ritardo</span> (progressi insufficienti), <span style='color:var(--red)'>Fermo</span> (nessun progresso misurabile). Gli indicatori misurano il contesto regionale: l'andamento non è attribuibile per intero all'azione della giunta (correlazione ≠ causalità). Dove indicato, i valori sono stime; i dati mancanti sono dichiarati.</p>"
  },
  status: {
    "in-linea": { label: "In linea",  cls: "s-green" },
    "in-corso": { label: "In corso",  cls: "s-blue"  },
    "ritardo":  { label: "In ritardo", cls: "s-amber" },
    "fermo":    { label: "Fermo",     cls: "s-red"   }
  },
  items: [
    { area:"Sanità", title:"Uscire dal commissariamento sanitario",
      promise:"Promessa centrale di Roberti: risanare i conti, salvare gli ospedali di area disagiata e riportare il Molise fuori dal piano di rientro.",
      cur:"2/3", curLbl:"macro-aree LEA sopra la soglia di sufficienza (2023)", base:"Regione in piano di rientro; insufficienza in prevenzione",
      delta:"1 area critica", deltaCls:"up-bad", deltaSub:"prevenzione sotto soglia", barPct:45, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Nel monitoraggio LEA 2023 il Molise resta insufficiente nella prevenzione. La regione dipende fortemente dalla mobilità sanitaria passiva e da strutture private accreditate; l'uscita dal commissariamento resta l'obiettivo dichiarato ma non raggiunto.",
      src:"Ministero della Salute — Nuovo Sistema di Garanzia", url:"https://www.salute.gov.it/new/it/news-e-media/notizie/livelli-essenziali-di-assistenza-sintesi-dei-risultati-del-nuovo-sistema-di/", asof:"2023 (relazione 2025)" },
    { area:"Sicurezza", title:"La regione con meno denunce d'Italia",
      promise:"Mantenere il primato di territorio più sicuro del Paese.",
      cur:"≈2.700", curLbl:"delitti denunciati ogni 100.000 abitanti (2022)", base:"media Italia: ≈3.800 ogni 100.000",
      delta:"-29% vs Italia", deltaCls:"up-good", deltaSub:"con le Marche, la più sicura", barPct:85, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Il Molise è con le Marche la regione con meno denunce in rapporto alla popolazione (2,7 ogni 100 abitanti nel 2022). I piccoli numeri rendono il tasso volatile. Valore arrotondato su dati ISTAT.",
      src:"ISTAT — Delitti denunciati (elab. Pagella Politica)", url:"https://pagellapolitica.it/articoli/mappe-denunce-reati-forze-ordine-italia", asof:"2022" },
    { area:"Lavoro", title:"Creare lavoro per trattenere i giovani",
      promise:"Il programma punta su ZES unica, automotive (Termoli) e credito alle PMI.",
      cur:"55,6%", curLbl:"tasso di occupazione 15-64 anni (2023, arrotondato)", base:"media Italia: 61,5% (2023)",
      delta:"-5,9 pt vs Italia", deltaCls:"up-bad", deltaSub:"sotto la media nazionale", barPct:56, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Occupazione sotto la media nazionale. L'incertezza sulla gigafactory di Termoli (progetto ACC/Stellantis più volte sospeso) pesa sul principale polo industriale regionale. Valore arrotondato: verificare su dati.istat.it.",
      src:"ISTAT — Rilevazione sulle forze di lavoro", url:"https://noi-italia.istat.it/pagina.php?id=3&categoria=16&action=show&L=0", asof:"2023" },
    { area:"Ambiente", title:"Differenziata sotto l'obiettivo",
      promise:"Impegni su gestione dei rifiuti e valorizzazione ambientale dei borghi.",
      cur:"58,4%", curLbl:"raccolta differenziata (2022)", base:"obiettivo di legge: 65%",
      delta:"-6,6 pt vs obiettivo", deltaCls:"up-bad", deltaSub:"sotto la soglia di legge", barPct:58, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"La raccolta differenziata resta sotto l'obiettivo di legge del 65%, pur in miglioramento negli ultimi anni. La gestione impiantistica su scala così piccola è strutturalmente difficile.",
      src:"ISPRA — Rapporto Rifiuti Urbani", url:"https://www.isprambiente.gov.it/it/istituto-informa/comunicati-stampa/anno-2024/rifiuti-urbani-nel-2023-cresce-dello-0-7-la-produzione", asof:"2022" },
    { area:"Spopolamento", title:"Fermare l'emorragia demografica",
      promise:"Il programma promette politiche per la residenzialità: incentivi ai giovani, servizi nei borghi e attrazione di nuovi abitanti.",
      cur:"<290 mila", curLbl:"residenti in regione, minimo storico", base:"≈313 mila residenti nel 2013",
      delta:"calo continuo", deltaCls:"up-bad", deltaSub:"il più rapido d'Italia in %", barPct:10, barCol:"var(--red)",
      status:"fermo", badge:"Fermo", bCls:"b-red",
      note:"Il Molise continua a perdere circa 2-3 mila residenti l'anno ed è sceso sotto quota 290 mila (dati demo.istat.it, valore arrotondato). Nessuna delle misure regionali ha finora invertito il trend, che riflette dinamiche nazionali amplificate.",
      src:"ISTAT — Bilancio demografico", url:"https://demo.istat.it/", asof:"2024" },
    { area:"Turismo", title:"«Il Molise esiste»: farne una destinazione",
      promise:"Il programma punta su borghi, tratturi e costa per trasformare l'anonimato mediatico in attrattiva turistica.",
      cur:"in crescita", curLbl:"presenze turistiche in aumento su base piccola", base:"regione con meno presenze in Italia",
      delta:"nicchia in espansione", deltaCls:"up-good", deltaSub:"numeri assoluti minimi", barPct:35, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Le presenze crescono in percentuale (base di partenza molto bassa: il Molise resta ultima regione italiana per flussi). Campagne come «Turismo è cultura» e i fondi di coesione finanziano borghi e cammini; il consuntivo puntuale è pubblicato da ISTAT sul turismo.",
      src:"ISTAT — Movimento turistico", url:"https://www.istat.it/statistiche-per-temi/imprese/turismo/", asof:"2024" }
  ]
};
