window.DASH = window.DASH || {};
window.DASH.piemonte = {
  meta: {
    nome: "Piemonte",
    area: "Nord",
    presidente: "Alberto Cirio",
    maggioranza: "centrodestra",
    stemma: "🐂"
  },
  ui: {
    h1: "Piemonte — Programma vs Realtà",
    sub: "Monitoraggio di 6 indicatori (4 comuni + 2 specifici) del programma della giunta Cirio II, in carica da giugno 2024.",
    metaHtml: "Dati aggiornati a <b>luglio 2026</b> · Fonti: Ministero della Salute, ISTAT, ISPRA, Ministero dell'Interno · <b>Il valore (KPI) è misurato; lo «stato» è una valutazione. Correlazione ≠ causalità.</b>",
    searchPlaceholder: "Cerca indicatore…",
    chipsAll: "Tutte le aree",
    hint: "Clicca una scheda per aprire dettaglio, nota e fonte.",
    emptyMsg: "Nessun indicatore corrisponde ai filtri.",
    startLabel: "Punto di partenza",
    noteLabel: "Nota",
    sourceLabel: "Fonte",
    footerHtml: "<p><b>Metodologia.</b> Quattro stati: <span style='color:var(--green)'>In linea</span> (obiettivo raggiunto), <span style='color:var(--blue)'>In corso</span> (progressi coerenti con l'impegno), <span style='color:var(--amber)'>In ritardo</span> (progressi insufficienti), <span style='color:var(--red)'>Fermo</span> (nessun progresso misurabile). Gli indicatori misurano il contesto regionale: l'andamento non è attribuibile per intero all'azione della giunta (correlazione ≠ causalità). Dove indicato, i valori sono stime o arrotondamenti; i dati mancanti sono dichiarati.</p>"
  },
  status: {
    "in-linea": { label: "In linea",  cls: "s-green" },
    "in-corso": { label: "In corso",  cls: "s-blue"  },
    "ritardo":  { label: "In ritardo", cls: "s-amber" },
    "fermo":    { label: "Fermo",     cls: "s-red"   }
  },
  items: [
    { area:"Sanità", title:"Garantire i LEA e ridurre le liste d'attesa",
      promise:"Il programma Cirio II mette la sanità al primo posto: abbattimento delle liste d'attesa e nuovi ospedali (Parco della Salute di Torino).",
      cur:"3/3", curLbl:"macro-aree LEA sopra la soglia di sufficienza (2023)", base:"Regione adempiente anche nella verifica 2022",
      delta:"adempiente", deltaCls:"up-good", deltaSub:"Nuovo Sistema di Garanzia", barPct:80, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Il Piemonte supera la soglia di 60 punti in tutte e tre le macro-aree (prevenzione, distrettuale, ospedaliera) del monitoraggio LEA 2023. Le liste d'attesa restano però un fronte critico segnalato dalle associazioni dei pazienti.",
      src:"Ministero della Salute — Nuovo Sistema di Garanzia", url:"https://www.salute.gov.it/new/it/news-e-media/notizie/livelli-essenziali-di-assistenza-sintesi-dei-risultati-del-nuovo-sistema-di/", asof:"2023 (relazione 2025)" },
    { area:"Sicurezza", title:"Città più sicure",
      promise:"Impegno del programma su sicurezza urbana, polizia locale e videosorveglianza nei comuni.",
      cur:"≈4.100", curLbl:"delitti denunciati ogni 100.000 abitanti (2022)", base:"media Italia: ≈3.800 ogni 100.000",
      delta:"+8% vs Italia", deltaCls:"up-bad", deltaSub:"sopra la media nazionale", barPct:55, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Il Piemonte è tra le regioni con più denunce in rapporto alla popolazione (Torino pesa molto sul dato). Valore arrotondato su dati ISTAT/Ministero dell'Interno 2022; il dato nazionale 2023 è in crescita (+3,8%).",
      src:"ISTAT — Delitti denunciati (elab. Pagella Politica)", url:"https://pagellapolitica.it/articoli/mappe-denunce-reati-forze-ordine-italia", asof:"2022" },
    { area:"Lavoro", title:"Più occupazione e competenze",
      promise:"Il programma punta su formazione professionale, attrazione di investimenti e rilancio dell'automotive.",
      cur:"66,9%", curLbl:"tasso di occupazione 15-64 anni (2023, arrotondato)", base:"media Italia: 61,5% (2023)",
      delta:"+5,4 pt vs Italia", deltaCls:"up-good", deltaSub:"sopra la media nazionale", barPct:67, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Occupazione sopra la media nazionale ma sotto le regioni leader del Nord (Emilia-Romagna e Trentino oltre il 70%). La crisi dell'automotive (Mirafiori) pesa sulle prospettive industriali. Valore arrotondato: verificare su dati.istat.it.",
      src:"ISTAT — Rilevazione sulle forze di lavoro", url:"https://noi-italia.istat.it/pagina.php?id=3&categoria=16&action=show&L=0", asof:"2023" },
    { area:"Ambiente", title:"Raccolta differenziata oltre il 65%",
      promise:"Obiettivi di economia circolare e qualità dell'aria nel bacino padano (accordi con le regioni confinanti).",
      cur:"67,0%", curLbl:"raccolta differenziata (2022)", base:"obiettivo di legge: 65%",
      delta:"+2,0 pt vs obiettivo", deltaCls:"up-good", deltaSub:"sopra la soglia di legge", barPct:67, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Obiettivo del 65% superato. Resta critica la qualità dell'aria: il bacino padano registra tra i peggiori valori europei di PM10 e NO2, con procedure di infrazione UE ancora aperte.",
      src:"ISPRA — Rapporto Rifiuti Urbani", url:"https://www.isprambiente.gov.it/it/istituto-informa/comunicati-stampa/anno-2024/rifiuti-urbani-nel-2023-cresce-dello-0-7-la-produzione", asof:"2022" },
    { area:"Infrastrutture", title:"Completare Asti-Cuneo e Torino-Lione",
      promise:"Il programma indica il completamento delle grandi opere (A33 Asti-Cuneo, Tav Torino-Lione) come leva di sviluppo.",
      cur:"1 su 2", curLbl:"grandi opere simbolo completate", base:"A33 incompiuta da oltre 30 anni a inizio mandato",
      delta:"A33 aperta", deltaCls:"up-good", deltaSub:"Torino-Lione in scavo", barPct:55, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"L'autostrada Asti-Cuneo è stata completata nel 2024. Per la Torino-Lione i cantieri del tunnel di base proseguono con orizzonte di apertura dopo il 2030: lo stato di avanzamento preciso a oggi non è disponibile in forma consolidata (stima: scavo in corso su più fronti).",
      src:"TELT — Tunnel Euralpin Lyon Turin", url:"https://www.telt.eu/it/", asof:"2025" },
    { area:"Turismo", title:"Fare del turismo una industria strategica",
      promise:"Obiettivo del programma: consolidare i record turistici post-pandemia tra Langhe, laghi e montagna.",
      cur:"≈15,5 mln", curLbl:"presenze turistiche annue (2023, stima)", base:"≈12,9 mln nel 2019, pre-pandemia (stima)",
      delta:"record storico", deltaCls:"up-good", deltaSub:"massimo mai registrato", barPct:75, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Il Piemonte ha comunicato per il 2023 il massimo storico di presenze, trainato da Langhe-Monferrato e Lago Maggiore. Valori indicati come stime: i consuntivi regionali definitivi sono pubblicati dall'Osservatorio turistico regionale.",
      src:"Visit Piemonte — Osservatorio turistico", url:"https://www.visitpiemonte-dmo.org/", asof:"2023" }
  ]
};
