window.DASH = window.DASH || {};
window.DASH.puglia = {
  meta: {
    nome: "Puglia",
    area: "Sud e Isole",
    presidente: "Antonio Decaro",
    maggioranza: "centrosinistra",
    stemma: "🫒"
  },
  ui: {
    h1: "Puglia — Programma vs Realtà",
    sub: "Monitoraggio di 6 indicatori (4 comuni + 2 specifici) del programma della giunta Decaro, eletta a novembre 2025 (64% dei voti) dopo i dieci anni di Emiliano.",
    metaHtml: "Dati aggiornati a <b>luglio 2026</b> · Fonti: Ministero della Salute, ISTAT, ISPRA, Ministero dell'Interno · <b>Il valore (KPI) è misurato; lo «stato» è una valutazione. Correlazione ≠ causalità.</b>",
    searchPlaceholder: "Cerca indicatore…",
    chipsAll: "Tutte le aree",
    hint: "Clicca una scheda per aprire dettaglio, nota e fonte.",
    emptyMsg: "Nessun indicatore corrisponde ai filtri.",
    startLabel: "Punto di partenza",
    noteLabel: "Nota",
    sourceLabel: "Fonte",
    footerHtml: "<p><b>Metodologia.</b> Quattro stati: <span style='color:var(--green)'>In linea</span> (obiettivo raggiunto), <span style='color:var(--blue)'>In corso</span> (progressi coerenti con l'impegno), <span style='color:var(--amber)'>In ritardo</span> (progressi insufficienti), <span style='color:var(--red)'>Fermo</span> (nessun progresso misurabile). La giunta è in carica da pochi mesi: molti indicatori fotografano l'eredità della gestione precedente. Correlazione ≠ causalità. Dove indicato, i valori sono stime; i dati mancanti sono dichiarati.</p>"
  },
  status: {
    "in-linea": { label: "In linea",  cls: "s-green" },
    "in-corso": { label: "In corso",  cls: "s-blue"  },
    "ritardo":  { label: "In ritardo", cls: "s-amber" },
    "fermo":    { label: "Fermo",     cls: "s-red"   }
  },
  items: [
    { area:"Sanità", title:"LEA raggiunti, liste d'attesa da abbattere",
      promise:"Primo impegno di Decaro: sanità di prossimità, liste d'attesa e assunzioni di personale nelle ASL pugliesi.",
      cur:"3/3", curLbl:"macro-aree LEA sopra la soglia di sufficienza (2023)", base:"Regione a lungo in piano di rientro",
      delta:"adempiente", deltaCls:"up-good", deltaSub:"punteggi da consolidare", barPct:62, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"La Puglia supera la soglia in tutte le macro-aree LEA 2023, ma liste d'attesa e pronto soccorso affollati sono stati il tema sanitario dominante della campagna elettorale 2025. Il programma promette risultati misurabili entro metà mandato.",
      src:"Ministero della Salute — Nuovo Sistema di Garanzia", url:"https://www.salute.gov.it/new/it/news-e-media/notizie/livelli-essenziali-di-assistenza-sintesi-dei-risultati-del-nuovo-sistema-di/", asof:"2023 (relazione 2025)" },
    { area:"Sicurezza", title:"Reati sotto la media, criminalità organizzata attiva",
      promise:"Impegni su sicurezza urbana (Bari, Foggia) e contrasto alla quarta mafia foggiana.",
      cur:"≈3.300", curLbl:"delitti denunciati ogni 100.000 abitanti (2022, stima)", base:"media Italia: ≈3.800 ogni 100.000",
      delta:"-13% vs Italia", deltaCls:"up-good", deltaSub:"Foggia sopra la media", barPct:58, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Denunce complessive sotto la media nazionale, ma il Foggiano resta un territorio ad alta densità di criminalità organizzata. Valore stimato e arrotondato su dati ISTAT 2022.",
      src:"ISTAT — Delitti denunciati", url:"http://dati.istat.it/Index.aspx?DataSetCode=dccv_delittips", asof:"2022 (stima)" },
    { area:"Lavoro", title:"Superare il 50% di occupazione è solo l'inizio",
      promise:"Il programma Decaro promette lavoro di qualità: contrasto al precariato e al caporalato, sostegno a industria e agroalimentare.",
      cur:"50,7%", curLbl:"tasso di occupazione 15-64 anni (2023)", base:"media Italia: 61,5% (2023)",
      delta:"-10,8 pt vs Italia", deltaCls:"up-bad", deltaSub:"divario ancora ampio", barPct:51, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"L'occupazione pugliese è cresciuta negli anni recenti ma resta oltre 10 punti sotto la media nazionale, con forte incidenza di lavoro stagionale e sommerso. Il dossier ex Ilva di Taranto è la più grande incognita occupazionale della legislatura.",
      src:"ISTAT — Rilevazione sulle forze di lavoro", url:"https://noi-italia.istat.it/pagina.php?id=3&categoria=16&action=show&L=0", asof:"2023" },
    { area:"Ambiente", title:"Differenziata sotto obiettivo, transizione di Taranto",
      promise:"Il programma promette economia circolare, decarbonizzazione dell'ex Ilva e tutela del territorio (Xylella, costa).",
      cur:"58,6%", curLbl:"raccolta differenziata (2022)", base:"obiettivo di legge: 65%",
      delta:"-6,4 pt vs obiettivo", deltaCls:"up-bad", deltaSub:"sotto la soglia di legge", barPct:59, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Raccolta differenziata sotto l'obiettivo di legge, in miglioramento. Il nodo ambientale simbolo resta l'ex Ilva di Taranto: la decarbonizzazione promessa da anni non ha ancora un percorso industriale definito.",
      src:"ISPRA — Rapporto Rifiuti Urbani", url:"https://www.isprambiente.gov.it/it/istituto-informa/comunicati-stampa/anno-2024/rifiuti-urbani-nel-2023-cresce-dello-0-7-la-produzione", asof:"2022" },
    { area:"Acqua", title:"Affrontare la crisi idrica strutturale",
      promise:"Priorità dichiarata di Decaro: nuove fonti (riuso, dissalazione), riduzione delle perdite di rete e tutela degli invasi in una regione a rischio siccità cronica.",
      cur:"emergenza ricorrente", curLbl:"invasi ai minimi nelle annate siccitose", base:"perdite di rete idrica intorno al 45-50% (stima ISTAT)",
      delta:"piani avviati", deltaCls:"up-good", deltaSub:"opere pluriennali", barPct:25, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"La Puglia dipende da fonti extraregionali e da invasi in sofferenza nelle annate siccitose; le perdite della rete restano tra le più alte d'Italia (dato ISTAT sul servizio idrico, valore indicativo). Dissalatori e riuso delle acque reflue sono programmati ma richiederanno anni.",
      src:"ISTAT — Censimento acque per uso civile", url:"https://www.istat.it/statistiche-per-temi/territorio-e-ambiente/acqua/", asof:"2024" },
    { area:"Energia", title:"Prima regione per eolico: governare la transizione",
      promise:"Il programma punta a fare della Puglia l'hub nazionale delle rinnovabili, con ricadute occupazionali e regole per il paesaggio.",
      cur:"1ª in Italia", curLbl:"potenza eolica installata tra le regioni", base:"quota rilevante anche nel fotovoltaico",
      delta:"primato consolidato", deltaCls:"up-good", deltaSub:"reti e accumuli da adeguare", barPct:75, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"La Puglia è storicamente la prima regione italiana per potenza eolica installata e tra le prime per fotovoltaico (dati Terna/GSE). La sfida della legislatura è trattenere valore aggiunto e occupazione, non solo ospitare impianti.",
      src:"Terna / GSE — statistiche rinnovabili", url:"https://www.terna.it/it/sistema-elettrico/statistiche", asof:"2024" }
  ]
};
