window.DASH = window.DASH || {};
window.DASH.sardegna = {
  meta: {
    nome: "Sardegna",
    area: "Sud e Isole",
    presidente: "Alessandra Todde",
    maggioranza: "centrosinistra (M5S-PD e alleati)",
    stemma: "🏝️"
  },
  ui: {
    h1: "Sardegna — Programma vs Realtà",
    sub: "Monitoraggio di 6 indicatori (4 comuni + 2 specifici) del programma della giunta Todde, in carica da marzo 2024 (caso decadenza chiuso a marzo 2026: Todde confermata).",
    metaHtml: "Dati aggiornati a <b>luglio 2026</b> · Fonti: Ministero della Salute, ISTAT, ISPRA, Ministero dell'Interno · <b>Il valore (KPI) è misurato; lo «stato» è una valutazione. Correlazione ≠ causalità.</b>",
    searchPlaceholder: "Cerca indicatore…",
    chipsAll: "Tutte le aree",
    hint: "Clicca una scheda per aprire dettaglio, nota e fonte.",
    emptyMsg: "Nessun indicatore corrisponde ai filtri.",
    startLabel: "Punto di partenza",
    noteLabel: "Nota",
    sourceLabel: "Fonte",
    footerHtml: "<p><b>Metodologia.</b> Quattro stati: <span style='color:var(--green)'>In linea</span> (obiettivo raggiunto), <span style='color:var(--blue)'>In corso</span> (progressi coerenti con l'impegno), <span style='color:var(--amber)'>In ritardo</span> (progressi insufficienti), <span style='color:var(--red)'>Fermo</span> (nessun progresso misurabile). Gli indicatori misurano il contesto regionale: l'andamento non è attribuibile per intero all'azione della giunta (correlazione ≠ causalità). Dove indicato, i valori sono stime; i dati mancanti sono dichiarati.</p>"
  },
  status: {
    "in-linea": { label: "In linea",  cls: "s-green" },
    "in-corso": { label: "In corso",  cls: "s-blue"  },
    "ritardo":  { label: "In ritardo", cls: "s-amber" },
    "fermo":    { label: "Fermo",     cls: "s-red"   }
  },
  items: [
    { area:"Sanità", title:"Ricucire la sanità dei territori",
      promise:"Priorità del programma Todde: superare la riforma sanitaria precedente, coprire i vuoti di organico e garantire i servizi nelle aree interne e nelle isole minori.",
      cur:"3/3", curLbl:"macro-aree LEA sopra la soglia di sufficienza (2023)", base:"Sardegna inadempiente in più verifiche precedenti",
      delta:"adempiente", deltaCls:"up-good", deltaSub:"risultato da consolidare", barPct:62, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Nel monitoraggio LEA 2023 la Sardegna supera la soglia in tutte le macro-aree, un miglioramento rispetto alle verifiche precedenti. Restano gravi le carenze di medici nei presidi periferici e i tempi dei pronto soccorso: qui si misura la promessa della giunta.",
      src:"Ministero della Salute — Nuovo Sistema di Garanzia", url:"https://www.salute.gov.it/new/it/news-e-media/notizie/livelli-essenziali-di-assistenza-sintesi-dei-risultati-del-nuovo-sistema-di/", asof:"2023 (relazione 2025)" },
    { area:"Sicurezza", title:"Tra le regioni con meno denunce",
      promise:"Impegni su sicurezza urbana e contrasto agli attacchi ai portavalori e ai bancomat nelle aree interne.",
      cur:"≈2.800", curLbl:"delitti denunciati ogni 100.000 abitanti (2022)", base:"media Italia: ≈3.800 ogni 100.000",
      delta:"-26% vs Italia", deltaCls:"up-good", deltaSub:"tra le più sicure d'Italia", barPct:78, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"La Sardegna è tra le regioni con meno denunce in rapporto alla popolazione (2,8 ogni 100 abitanti nel 2022). Valore arrotondato su dati ISTAT.",
      src:"ISTAT — Delitti denunciati (elab. Pagella Politica)", url:"https://pagellapolitica.it/articoli/mappe-denunce-reati-forze-ordine-italia", asof:"2022" },
    { area:"Lavoro", title:"Lavoro stabile oltre la stagionalità turistica",
      promise:"Il programma promette lavoro di qualità: contrasto alla precarietà stagionale, vertenze industriali (Portovesme) e sostegno alle imprese locali.",
      cur:"55,6%", curLbl:"tasso di occupazione 15-64 anni (2023, arrotondato)", base:"media Italia: 61,5% (2023)",
      delta:"-5,9 pt vs Italia", deltaCls:"up-bad", deltaSub:"sotto la media nazionale", barPct:56, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Occupazione sotto la media nazionale e fortemente stagionale. Le vertenze industriali del Sulcis (Portovesme) e la transizione energetica dell'isola sono i dossier occupazionali più pesanti. Valore arrotondato: verificare su dati.istat.it.",
      src:"ISTAT — Rilevazione sulle forze di lavoro", url:"https://noi-italia.istat.it/pagina.php?id=3&categoria=16&action=show&L=0", asof:"2023" },
    { area:"Ambiente", title:"Terza regione per raccolta differenziata",
      promise:"Impegni su economia circolare e tutela delle coste (l'isola ha già limiti severi al consumo di suolo costiero).",
      cur:"76,3%", curLbl:"raccolta differenziata (2023)", base:"obiettivo di legge: 65%",
      delta:"+11,3 pt vs obiettivo", deltaCls:"up-good", deltaSub:"terza regione d'Italia", barPct:76, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Con il 76,3% nel 2023 la Sardegna è terza in Italia per raccolta differenziata, unica regione del Mezzogiorno ai vertici. Un risultato costruito in oltre un decennio di gestione consortile.",
      src:"ISPRA — Rapporto Rifiuti Urbani 2024", url:"https://www.isprambiente.gov.it/it/istituto-informa/comunicati-stampa/anno-2024/rifiuti-urbani-nel-2023-cresce-dello-0-7-la-produzione", asof:"2023" },
    { area:"Energia", title:"Governare l'assalto eolico: la legge aree idonee",
      promise:"Promessa fondativa della giunta Todde: fermare la speculazione energetica sull'isola con moratoria e legge sulle aree idonee, tutelando paesaggio e comunità.",
      cur:"legge approvata", curLbl:"moratoria (2024) e legge aree idonee in vigore", base:"boom di richieste di connessione eolico/fotovoltaico a inizio mandato",
      delta:"contenziosi aperti", deltaCls:"up-bad", deltaSub:"impugnazioni e ricorsi", barPct:55, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"La giunta ha approvato la moratoria di 18 mesi (giugno 2024) e poi la legge sulle aree idonee (dicembre 2024). L'efficacia reale dipende dai contenziosi: parti della normativa sono state impugnate davanti a Corte costituzionale e TAR, con esiti ancora in evoluzione.",
      src:"Regione Sardegna — legge aree idonee", url:"https://www.regione.sardegna.it/", asof:"2024-2025" },
    { area:"Trasporti", title:"Continuità territoriale aerea e navale",
      promise:"Il programma promette una vertenza con lo Stato per una continuità territoriale degna: più voli, tariffe eque e collegamenti anche d'inverno.",
      cur:"parziale", curLbl:"nuovi bandi di continuità aerea in vigore", base:"regime storico con frequenze e tariffe contestate",
      delta:"miglioramenti limitati", deltaCls:"up-bad", deltaSub:"dossier aperto con Roma e Bruxelles", barPct:35, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"I bandi di continuità territoriale sono stati rinnovati ma il modello resta quello contestato: frequenze insufficienti nei picchi e tariffe non competitive per i non residenti. La riforma strutturale promessa (anche in sede UE) non è stata ancora ottenuta.",
      src:"Regione Sardegna — continuità territoriale", url:"https://www.regione.sardegna.it/argomenti/trasporti/", asof:"2025" }
  ]
};
