window.DASH = window.DASH || {};
window.DASH.sicilia = {
  meta: {
    nome: "Sicilia",
    area: "Sud e Isole",
    presidente: "Renato Schifani",
    maggioranza: "centrodestra",
    stemma: "🔱"
  },
  ui: {
    h1: "Sicilia — Programma vs Realtà",
    sub: "Monitoraggio di 6 indicatori (4 comuni + 2 specifici) del programma della giunta Schifani, in carica da ottobre 2022.",
    metaHtml: "Dati aggiornati a <b>luglio 2026</b> · Fonti: Ministero della Salute, ISTAT, ISPRA, Ministero dell'Interno · <b>Il valore (KPI) è misurato; lo «stato» è una valutazione. Correlazione ≠ causalità.</b>",
    searchPlaceholder: "Cerca indicatore…",
    chipsAll: "Tutte le aree",
    hint: "Clicca una scheda per aprire dettaglio, nota e fonte.",
    emptyMsg: "Nessun indicatore corrisponde ai filtri.",
    startLabel: "Punto di partenza",
    noteLabel: "Nota",
    sourceLabel: "Fonte",
    footerHtml: "<p><b>Metodologia.</b> Quattro stati: <span style='color:var(--green)'>In linea</span> (obiettivo raggiunto), <span style='color:var(--blue)'>In corso</span> (progressi coerenti con l'impegno), <span style='color:var(--amber)'>In ritardo</span> (progressi insufficienti), <span style='color:var(--red)'>Fermo</span> (nessun progresso misurabile). Gli indicatori misurano il contesto regionale: l'andamento non è attribuibile per intero all'azione della giunta (correlazione ≠ causalità). Dove indicato, i valori sono stime; i dati mancanti sono dichiarati.</p>"
  },
  status: {
    "in-linea": { label: "In linea",  cls: "s-green" },
    "in-corso": { label: "In corso",  cls: "s-blue"  },
    "ritardo":  { label: "In ritardo", cls: "s-amber" },
    "fermo":    { label: "Fermo",     cls: "s-red"   }
  },
  items: [
    { area:"Sanità", title:"Riportare i LEA alla sufficienza",
      promise:"Il programma Schifani promette il potenziamento della rete ospedaliera e territoriale e la riduzione dei viaggi della speranza verso il Nord.",
      cur:"1/3", curLbl:"macro-aree LEA sopra la soglia di sufficienza (2023)", base:"insufficienze in prevenzione e distrettuale",
      delta:"2 aree critiche", deltaCls:"up-bad", deltaSub:"prevenzione e distrettuale", barPct:28, barCol:"var(--red)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Nel monitoraggio LEA 2023 la Sicilia è insufficiente in due macro-aree su tre (prevenzione e distrettuale). Liste d'attesa, pronto soccorso e mobilità passiva restano tra i peggiori indicatori nazionali; la sanità è il principale terreno di scontro politico regionale.",
      src:"Ministero della Salute — Nuovo Sistema di Garanzia", url:"https://www.salute.gov.it/new/it/news-e-media/notizie/livelli-essenziali-di-assistenza-sintesi-dei-risultati-del-nuovo-sistema-di/", asof:"2023 (relazione 2025)" },
    { area:"Sicurezza", title:"Denunce sotto la media, mafia presente",
      promise:"Impegni su legalità e sicurezza urbana nelle aree metropolitane.",
      cur:"≈3.300", curLbl:"delitti denunciati ogni 100.000 abitanti (2022, stima)", base:"media Italia: ≈3.800 ogni 100.000",
      delta:"-13% vs Italia", deltaCls:"up-good", deltaSub:"dato da leggere con cautela", barPct:55, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Denunce per abitante sotto la media nazionale, con valori più alti nelle città metropolitane. Come per altre regioni a forte presenza mafiosa, la propensione alla denuncia più bassa rende il confronto interregionale poco affidabile. Valore stimato su dati ISTAT 2022.",
      src:"ISTAT — Delitti denunciati", url:"http://dati.istat.it/Index.aspx?DataSetCode=dccv_delittips", asof:"2022 (stima)" },
    { area:"Lavoro", title:"Occupazione: terzultima in Italia",
      promise:"Il programma punta su ZES unica, termovalorizzatori e grandi opere per creare lavoro.",
      cur:"44,9%", curLbl:"tasso di occupazione 15-64 anni (2023)", base:"media Italia: 61,5% (2023)",
      delta:"-16,6 pt vs Italia", deltaCls:"up-bad", deltaSub:"terzultima in Italia", barPct:45, barCol:"var(--red)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Il tasso di occupazione siciliano (44,9% nel 2023) è terzultimo in Italia, con occupazione femminile sotto il 35%. Il 2024-2025 ha mostrato una crescita dell'occupazione nel Mezzogiorno, ma il divario strutturale resta superiore ai 15 punti.",
      src:"ISTAT — Rilevazione sulle forze di lavoro", url:"https://noi-italia.istat.it/pagina.php?id=3&categoria=16&action=show&L=0", asof:"2023" },
    { area:"Ambiente", title:"Ultima per raccolta differenziata",
      promise:"Il programma promette i termovalorizzatori (Palermo e Catania) e la fine delle discariche come soluzione al ciclo dei rifiuti.",
      cur:"51,5%", curLbl:"raccolta differenziata (2022)", base:"obiettivo di legge: 65%",
      delta:"-13,5 pt vs obiettivo", deltaCls:"up-bad", deltaSub:"ultima tra le regioni", barPct:52, barCol:"var(--red)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"La Sicilia ha superato per la prima volta il 50% nel 2022 ma resta ultima in Italia, con dipendenza dalle discariche. I due termovalorizzatori annunciati da Schifani sono in iter autorizzativo-progettuale: nessuno è in esercizio.",
      src:"ISPRA — Rapporto Rifiuti Urbani", url:"https://www.isprambiente.gov.it/it/istituto-informa/comunicati-stampa/anno-2024/rifiuti-urbani-nel-2023-cresce-dello-0-7-la-produzione", asof:"2022" },
    { area:"Acqua", title:"Uscire dall'emergenza idrica",
      promise:"Dopo la siccità record del 2024 (stato di emergenza nazionale), la giunta promette dissalatori riattivati, invasi manutenuti e reti riparate.",
      cur:"emergenza", curLbl:"crisi idrica ricorrente; razionamenti in molti comuni", base:"2024: invasi ai minimi storici, agricoltura in ginocchio",
      delta:"interventi parziali", deltaCls:"up-bad", deltaSub:"dissalatori in riattivazione", barPct:20, barCol:"var(--red)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"La crisi idrica 2024 ha imposto razionamenti a milioni di siciliani. La Regione ha avviato la riattivazione dei dissalatori (Trapani, Porto Empedocle, Gela) e interventi su pozzi e reti, ma le perdite idriche restano oltre il 50% (ISTAT) e l'approvvigionamento resta fragile nelle annate secche.",
      src:"ISTAT — Censimento acque / Protezione Civile", url:"https://www.istat.it/statistiche-per-temi/territorio-e-ambiente/acqua/", asof:"2024-2025" },
    { area:"Ponte e trasporti", title:"Ponte sullo Stretto e ferrovie interne",
      promise:"La giunta sostiene il Ponte sullo Stretto come opera trasformativa, insieme al raddoppio ferroviario Palermo-Catania-Messina.",
      cur:"in costruzione", curLbl:"cronoprogramma 2026-2034 approvato; cantieri attesi entro fine 2026", base:"progetto rilanciato dal governo nazionale nel 2023",
      delta:"avvio imminente", deltaCls:"up-good", deltaSub:"cantieri attesi entro fine anno", barPct:40, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Il Ponte sullo Stretto (competenza statale, sostenuto dalla Regione) ha ottenuto il cronoprogramma definitivo 2026-2034 a luglio 2026. I cantieri sono attesi nell'ultimo trimestre del 2026, con completamento previsto nel 2034. Costi 10,5 miliardi di euro. Il raddoppio ferroviario Palermo-Catania procedono con fondi PNRR.",
      src:"Ministero delle Infrastrutture / Stretto di Messina S.p.A.", url:"https://www.mit.gov.it/comunicazione/news/ponte-sullo-stretto-il-cipess-approva-il-progetto-definitivo", asof:"luglio 2026" }
  ]
};
