window.DASH = window.DASH || {};
window.DASH.toscana = {
  meta: {
    nome: "Toscana",
    area: "Centro",
    presidente: "Eugenio Giani",
    maggioranza: "centrosinistra",
    stemma: "⚜️"
  },
  ui: {
    h1: "Toscana — Programma vs Realtà",
    sub: "Monitoraggio di 6 indicatori (4 comuni + 2 specifici) del programma della giunta Giani II, rieletta a ottobre 2025 (circa 54% dei voti).",
    metaHtml: "Dati aggiornati a <b>luglio 2026</b> · Fonti: Ministero della Salute, ISTAT, ISPRA, Ministero dell'Interno · <b>Il valore (KPI) è misurato; lo «stato» è una valutazione. Correlazione ≠ causalità.</b>",
    searchPlaceholder: "Cerca indicatore…",
    chipsAll: "Tutte le aree",
    hint: "Clicca una scheda per aprire dettaglio, nota e fonte.",
    emptyMsg: "Nessun indicatore corrisponde ai filtri.",
    startLabel: "Punto di partenza",
    noteLabel: "Nota",
    sourceLabel: "Fonte",
    footerHtml: "<p><b>Metodologia.</b> Quattro stati: <span style='color:var(--green)'>In linea</span> (obiettivo raggiunto), <span style='color:var(--blue)'>In corso</span> (progressi coerenti con l'impegno), <span style='color:var(--amber)'>In ritardo</span> (progressi insufficienti), <span style='color:var(--red)'>Fermo</span> (nessun progresso misurabile). Gli indicatori misurano il contesto regionale: l'andamento non è attribuibile per intero all'azione della giunta (correlazione ≠ causalità). Dove indicato, i valori sono stime; i dati mancanti sono dichiarati.</p>"
  },
  status: {
    "in-linea": { label: "In linea",  cls: "s-green" },
    "in-corso": { label: "In corso",  cls: "s-blue"  },
    "ritardo":  { label: "In ritardo", cls: "s-amber" },
    "fermo":    { label: "Fermo",     cls: "s-red"   }
  },
  items: [
    { area:"Sanità", title:"LEA garantiti, attese da ridurre",
      promise:"Il programma Giani II promette il rafforzamento della sanità territoriale e tempi di attesa in linea col piano nazionale.",
      cur:"3/3", curLbl:"macro-aree LEA sopra la soglia di sufficienza (2023)", base:"Regione storicamente tra le prime nel monitoraggio",
      delta:"adempiente", deltaCls:"up-good", deltaSub:"tra i punteggi più alti", barPct:83, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"La Toscana supera la soglia in tutte le macro-aree LEA 2023, con punteggi tra i migliori. Il disavanzo sanitario regionale e le attese per la specialistica restano i punti critici discussi in Consiglio.",
      src:"Ministero della Salute — Nuovo Sistema di Garanzia", url:"https://www.salute.gov.it/new/it/news-e-media/notizie/livelli-essenziali-di-assistenza-sintesi-dei-risultati-del-nuovo-sistema-di/", asof:"2023 (relazione 2025)" },
    { area:"Sicurezza", title:"Sicurezza nelle città d'arte",
      promise:"Impegni su sicurezza urbana e vivibilità nelle aree ad alta pressione turistica.",
      cur:"≈4.200", curLbl:"delitti denunciati ogni 100.000 abitanti (2022)", base:"media Italia: ≈3.800 ogni 100.000",
      delta:"+11% vs Italia", deltaCls:"up-bad", deltaSub:"Firenze tra le prime province", barPct:48, barCol:"var(--amber)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"La Toscana è quinta tra le regioni per denunce in rapporto alla popolazione; Firenze è stabilmente tra le prime province d'Italia (effetto dei flussi turistici sul rapporto reati/residenti). Valore arrotondato, dati 2022.",
      src:"ISTAT / Il Sole 24 Ore — Indice della criminalità", url:"https://lab24.ilsole24ore.com/indice-della-criminalita/", asof:"2022" },
    { area:"Lavoro", title:"Occupazione stabile sopra la media",
      promise:"Il programma punta su distretti industriali, moda e turismo per difendere l'occupazione nelle crisi di settore.",
      cur:"67,4%", curLbl:"tasso di occupazione 15-64 anni (2023, arrotondato)", base:"media Italia: 61,5% (2023)",
      delta:"+5,9 pt vs Italia", deltaCls:"up-good", deltaSub:"prima del Centro", barPct:67, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Occupazione sopra la media nazionale, ma la crisi del distretto moda-pelletteria (Firenze, Arezzo) ha aperto vertenze significative con ricorso massiccio alla cassa integrazione. Valore arrotondato.",
      src:"ISTAT — Rilevazione sulle forze di lavoro", url:"https://noi-italia.istat.it/pagina.php?id=3&categoria=16&action=show&L=0", asof:"2023" },
    { area:"Ambiente", title:"Portare la differenziata sopra il 65%",
      promise:"Il programma promette il completamento dell'impiantistica per i rifiuti e l'economia circolare dei distretti (cartario, conciario).",
      cur:"65,6%", curLbl:"raccolta differenziata (2022)", base:"obiettivo di legge: 65%",
      delta:"+0,6 pt vs obiettivo", deltaCls:"up-good", deltaSub:"appena sopra la soglia", barPct:66, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Obiettivo di legge appena raggiunto, sotto la media delle regioni del Centro-Nord più virtuose. Il nodo storico è l'impiantistica: la regione dipende ancora da smaltimenti fuori territorio per parte dei flussi.",
      src:"ISPRA — Rapporto Rifiuti Urbani", url:"https://www.isprambiente.gov.it/it/istituto-informa/comunicati-stampa/anno-2024/rifiuti-urbani-nel-2023-cresce-dello-0-7-la-produzione", asof:"2022" },
    { area:"Infrastrutture", title:"Completare le tramvie fiorentine e la Darsena Europa",
      promise:"Il programma indica tramvie di Firenze, aeroporti e porto di Livorno (Darsena Europa) come opere prioritarie della legislatura.",
      cur:"in cantiere", curLbl:"nuove linee tramviarie in costruzione a Firenze", base:"rete esistente: linee T1 e T2",
      delta:"avanzamento", deltaCls:"up-good", deltaSub:"apertura prevista in legislatura", barPct:55, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"L'estensione della rete tramviaria fiorentina (linea per Bagno a Ripoli e ulteriori tratte) è in costruzione con finanziamenti PNRR; la Darsena Europa a Livorno è in fase realizzativa. Le date di apertura sono state più volte aggiornate: percentuali di avanzamento puntuali non disponibili in forma consolidata.",
      src:"Comune di Firenze / Regione Toscana — grandi opere", url:"https://www.regione.toscana.it/", asof:"2025" },
    { area:"Energia", title:"Geotermia come petrolio verde della Toscana",
      promise:"Il programma promette il rilancio della geotermia (nuove concessioni e impianti) come pilastro energetico regionale.",
      cur:"≈6 TWh", curLbl:"produzione geotermoelettrica annua (stima)", base:"circa un terzo del fabbisogno elettrico regionale",
      delta:"unica in Italia", deltaCls:"up-good", deltaSub:"riassegnazione concessioni in corso", barPct:70, barCol:"var(--green)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"La Toscana è l'unica regione italiana con produzione geotermoelettrica industriale (circa 6 TWh l'anno, valore indicativo Terna/Enel Green Power), pari a circa un terzo dei consumi elettrici regionali. La partita in corso riguarda il rinnovo delle concessioni e i nuovi investimenti.",
      src:"Terna — dati statistici sull'energia elettrica", url:"https://www.terna.it/it/sistema-elettrico/statistiche", asof:"2024 (stima)" }
  ]
};
