window.DASH = window.DASH || {};
window.DASH.trentinoaltoadige = {
  meta: {
    nome: "Trentino-Alto Adige",
    area: "Nord",
    presidente: "Arno Kompatscher (staffetta con Maurizio Fugatti sospesa)",
    maggioranza: "autonomisti (SVP, Lega e alleati)",
    stemma: "🦅"
  },
  ui: {
    h1: "Trentino-Alto Adige — Programma vs Realtà",
    sub: "Monitoraggio di 6 indicatori (4 comuni + 2 specifici). La Regione ha poteri limitati: gran parte delle competenze è delle Province autonome di Trento (Fugatti) e Bolzano (Kompatscher).",
    metaHtml: "Dati aggiornati a <b>luglio 2026</b> · Fonti: Ministero della Salute, ISTAT, ISPRA, Ministero dell'Interno · <b>Il valore (KPI) è misurato; lo «stato» è una valutazione. Correlazione ≠ causalità.</b>",
    searchPlaceholder: "Cerca indicatore…",
    chipsAll: "Tutte le aree",
    hint: "Clicca una scheda per aprire dettaglio, nota e fonte.",
    emptyMsg: "Nessun indicatore corrisponde ai filtri.",
    startLabel: "Punto di partenza",
    noteLabel: "Nota",
    sourceLabel: "Fonte",
    footerHtml: "<p><b>Metodologia.</b> Quattro stati: <span style='color:var(--green)'>In linea</span> (obiettivo raggiunto), <span style='color:var(--blue)'>In corso</span> (progressi coerenti con l'impegno), <span style='color:var(--amber)'>In ritardo</span> (progressi insufficienti), <span style='color:var(--red)'>Fermo</span> (nessun progresso misurabile). Gli indicatori misurano il contesto regionale: l'andamento non è attribuibile per intero all'azione della giunta (correlazione ≠ causalità). Dove indicato, i valori sono stime o arrotondamenti; i dati mancanti sono dichiarati.</p>"
  },
  status: {
    "in-linea": { label: "In linea",  cls: "s-green" },
    "in-corso": { label: "In corso",  cls: "s-blue"  },
    "ritardo":  { label: "In ritardo", cls: "s-amber" },
    "fermo":    { label: "Fermo",     cls: "s-red"   }
  },
  items: [
    { area:"Sanità", title:"LEA garantiti nelle due Province",
      promise:"I programmi provinciali promettono sanità di prossimità nelle valli e riduzione delle attese, con il nodo della carenza di medici (anche per il bilinguismo a Bolzano).",
      cur:"Trento 3/3", curLbl:"macro-aree LEA sufficienti; Bolzano 2/3 (2023)", base:"Bolzano già insufficiente in prevenzione nelle verifiche precedenti",
      delta:"1 area critica", deltaCls:"up-bad", deltaSub:"prevenzione a Bolzano", barPct:70, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Nel monitoraggio LEA 2023 la PA di Trento è sufficiente in tutte e tre le macro-aree, mentre la PA di Bolzano resta sotto soglia nella prevenzione (dove pesano anche le coperture vaccinali più basse d'Italia).",
      src:"Ministero della Salute — Nuovo Sistema di Garanzia", url:"https://www.salute.gov.it/new/it/news-e-media/notizie/livelli-essenziali-di-assistenza-sintesi-dei-risultati-del-nuovo-sistema-di/", asof:"2023 (relazione 2025)" },
    { area:"Sicurezza", title:"Territorio tra i più sicuri",
      promise:"Impegni dei programmi provinciali su sicurezza urbana a Trento e Bolzano e presidio del Brennero.",
      cur:"≈3.300", curLbl:"delitti denunciati ogni 100.000 abitanti (2022, stima)", base:"media Italia: ≈3.800 ogni 100.000",
      delta:"-13% vs Italia", deltaCls:"up-good", deltaSub:"sotto la media nazionale", barPct:70, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Denunce sotto la media nazionale. Valore stimato e arrotondato su dati ISTAT/Ministero dell'Interno 2022; i capoluoghi registrano tassi più alti della media delle valli.",
      src:"ISTAT — Delitti denunciati", url:"http://dati.istat.it/Index.aspx?DataSetCode=dccv_delittips", asof:"2022 (stima)" },
    { area:"Lavoro", title:"Piena occupazione",
      promise:"Obiettivo dichiarato dei programmi provinciali: mantenere la piena occupazione e attrarre lavoratori qualificati.",
      cur:"70,7%", curLbl:"tasso di occupazione 15-64 anni (2023, arrotondato)", base:"media Italia: 61,5% (2023)",
      delta:"+9,2 pt vs Italia", deltaCls:"up-good", deltaSub:"Bolzano al vertice nazionale", barPct:71, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Il tasso di occupazione regionale è tra i più alti d'Italia, con la PA di Bolzano stabilmente prima o seconda a livello nazionale. Il problema segnalato dalle imprese è la carenza di manodopera, aggravata dal costo della casa. Valore arrotondato.",
      src:"ISTAT — Rilevazione sulle forze di lavoro", url:"https://noi-italia.istat.it/pagina.php?id=3&categoria=16&action=show&L=0", asof:"2023" },
    { area:"Ambiente", title:"Differenziata tra le migliori",
      promise:"Impegni su economia circolare, mobilità elettrica e riduzione del traffico pesante lungo l'asse del Brennero.",
      cur:"74,7%", curLbl:"raccolta differenziata (2022)", base:"obiettivo di legge: 65%",
      delta:"+9,7 pt vs obiettivo", deltaCls:"up-good", deltaSub:"terza tra le regioni", barPct:75, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Raccolta differenziata ampiamente sopra l'obiettivo di legge. Resta aperto il dossier del traffico merci sull'A22 e dell'inquinamento da NO2 lungo la valle dell'Adige.",
      src:"ISPRA — Rapporto Rifiuti Urbani", url:"https://www.isprambiente.gov.it/it/istituto-informa/comunicati-stampa/anno-2024/rifiuti-urbani-nel-2023-cresce-dello-0-7-la-produzione", asof:"2022" },
    { area:"Autonomia", title:"Riforma dello Statuto di autonomia",
      promise:"Priorità condivisa di SVP e alleati: recuperare le competenze erose dalle sentenze costituzionali e aggiornare lo Statuto speciale.",
      cur:"iter avanzato", curLbl:"Senato ha approvato la riforma costituzionale (maggio 2026)", base:"trattativa Stato-Province avviata nel 2023",
      delta:"via libera Senato", deltaCls:"up-good", deltaSub:"prossima la discussione in Commissione Affari costituzionali Camera", barPct:65, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Il disegno di legge costituzionale di riforma dello Statuto, frutto dell'intesa tra Governo e Province autonome, ha ottenuto il via libera del Senato il 13 maggio 2026 (approvazione definitiva del Senato). La riforma restituisce competenze autonome limitate in protezione civile, professioni, previdenza. Intanto la staffetta regionale Kompatscher-Fugatti rimane sospesa (maggio 2026).",
      src:"Ministero degli Affari Regionali — Riforma Statuto TAA", url:"https://www.gazzettaufficiale.it/eli/id/2026/05/23/25R00314/S3", asof:"maggio 2026" },
    { area:"Turismo", title:"Gestire il successo turistico",
      promise:"I programmi provinciali puntano su qualità e limiti alla pressione turistica (tetto ai posti letto in Alto Adige).",
      cur:"≈55 mln", curLbl:"presenze annue nelle due Province (stima)", base:"Alto Adige ≈37 mln, Trentino ≈18-19 mln",
      delta:"record storici", deltaCls:"up-good", deltaSub:"pressione in aumento", barPct:80, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Le due Province sommano il maggior flusso turistico alpino d'Italia, con record ripetuti dopo la pandemia. Valori stimati dagli istituti di statistica provinciali (ASTAT e ISPAT); Bolzano ha introdotto un tetto ai posti letto per contenere l'overtourism.",
      src:"ASTAT Bolzano / ISPAT Trento", url:"https://astat.provincia.bz.it/", asof:"2024 (stima)" }
  ]
};
