window.DASH = window.DASH || {};
window.DASH.umbria = {
  meta: {
    nome: "Umbria",
    area: "Centro",
    presidente: "Stefania Proietti",
    maggioranza: "centrosinistra",
    stemma: "🕊️"
  },
  ui: {
    h1: "Umbria — Programma vs Realtà",
    sub: "Monitoraggio di 6 indicatori (4 comuni + 2 specifici) del programma della giunta Proietti, in carica da dicembre 2024.",
    metaHtml: "Dati aggiornati a <b>luglio 2026</b> · Fonti: Ministero della Salute, ISTAT, ISPRA, Ministero dell'Interno · <b>Il valore (KPI) è misurato; lo «stato» è una valutazione. Correlazione ≠ causalità.</b>",
    searchPlaceholder: "Cerca indicatore…",
    chipsAll: "Tutte le aree",
    hint: "Clicca una scheda per aprire dettaglio, nota e fonte.",
    emptyMsg: "Nessun indicatore corrisponde ai filtri.",
    startLabel: "Punto di partenza",
    noteLabel: "Nota",
    sourceLabel: "Fonte",
    footerHtml: "<p><b>Metodologia.</b> Quattro stati: <span style='color:var(--green)'>In linea</span> (obiettivo raggiunto), <span style='color:var(--blue)'>In corso</span> (progressi coerenti con l'impegno), <span style='color:var(--amber)'>In ritardo</span> (progressi insufficienti), <span style='color:var(--red)'>Fermo</span> (nessun progresso misurabile). Gli indicatori misurano il contesto regionale: l'andamento non è attribuibile per intero all'azione della giunta (correlazione ≠ causalità). Dove indicato, i valori sono stime; i dati mancanti sono dichiarati.</p>"
  },
  status: {
    "in-linea": { label: "In linea",  cls: "s-green" },
    "in-corso": { label: "In corso",  cls: "s-blue"  },
    "ritardo":  { label: "In ritardo", cls: "s-amber" },
    "fermo":    { label: "Fermo",     cls: "s-red"   }
  },
  items: [
    { area:"Sanità", title:"Sanità pubblica al centro del mandato",
      promise:"Proietti ha vinto promettendo il rilancio della sanità pubblica umbra: meno liste d'attesa e riorganizzazione delle aziende sanitarie.",
      cur:"3/3", curLbl:"macro-aree LEA sopra la soglia di sufficienza (2023)", base:"Regione adempiente anche nelle verifiche precedenti",
      delta:"adempiente", deltaCls:"up-good", deltaSub:"Nuovo Sistema di Garanzia", barPct:75, barCol:"var(--green)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"L'Umbria supera la soglia in tutte le macro-aree LEA 2023. Lo stato è «in corso» perché la promessa centrale (liste d'attesa e disavanzo sanitario ereditato) si misura su indicatori più fini: la giunta ha aperto il mandato con una manovra fiscale per coprire i conti della sanità, molto contestata.",
      src:"Ministero della Salute — Nuovo Sistema di Garanzia", url:"https://www.salute.gov.it/new/it/news-e-media/notizie/livelli-essenziali-di-assistenza-sintesi-dei-risultati-del-nuovo-sistema-di/", asof:"2023 (relazione 2025)" },
    { area:"Sicurezza", title:"Territorio mediamente sicuro",
      promise:"Impegni su sicurezza urbana a Perugia e Terni e contrasto allo spaccio.",
      cur:"≈3.400", curLbl:"delitti denunciati ogni 100.000 abitanti (2022, stima)", base:"media Italia: ≈3.800 ogni 100.000",
      delta:"-11% vs Italia", deltaCls:"up-good", deltaSub:"sotto la media nazionale", barPct:62, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Denunce sotto la media nazionale, con Perugia sopra la media regionale. Valore stimato e arrotondato su dati ISTAT/Ministero dell'Interno 2022.",
      src:"ISTAT — Delitti denunciati", url:"http://dati.istat.it/Index.aspx?DataSetCode=dccv_delittips", asof:"2022 (stima)" },
    { area:"Lavoro", title:"Rilanciare salari e lavoro qualificato",
      promise:"Il programma punta su reindustrializzazione (crisi Ast Terni superata), ricerca e trattenimento dei giovani laureati.",
      cur:"65,4%", curLbl:"tasso di occupazione 15-64 anni (2023, arrotondato)", base:"media Italia: 61,5% (2023)",
      delta:"+3,9 pt vs Italia", deltaCls:"up-good", deltaSub:"sopra la media, salari bassi", barPct:65, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Occupazione sopra la media nazionale, ma con retribuzioni medie tra le più basse del Centro-Nord e forte emigrazione giovanile qualificata. Valore arrotondato: verificare su dati.istat.it.",
      src:"ISTAT — Rilevazione sulle forze di lavoro", url:"https://noi-italia.istat.it/pagina.php?id=3&categoria=16&action=show&L=0", asof:"2023" },
    { area:"Ambiente", title:"Differenziata oltre il 65%",
      promise:"Il programma promette la chiusura del ciclo dei rifiuti senza inceneritore e la tutela delle acque (lago Trasimeno).",
      cur:"67,9%", curLbl:"raccolta differenziata (2022)", base:"obiettivo di legge: 65%",
      delta:"+2,9 pt vs obiettivo", deltaCls:"up-good", deltaSub:"sopra la soglia di legge", barPct:68, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Obiettivo di legge superato. Il dossier ambientale più delicato è la crisi idrica del lago Trasimeno, ai minimi storici di livello negli anni recenti di siccità.",
      src:"ISPRA — Rapporto Rifiuti Urbani", url:"https://www.isprambiente.gov.it/it/istituto-informa/comunicati-stampa/anno-2024/rifiuti-urbani-nel-2023-cresce-dello-0-7-la-produzione", asof:"2022" },
    { area:"Trasporti", title:"Collegare una regione senza mare né alta velocità",
      promise:"Il programma promette il rilancio dell'aeroporto di Perugia, il potenziamento ferroviario (Roma in meno di 2 ore) e la FCU riattivata.",
      cur:"record", curLbl:"passeggeri annui aeroporto di Perugia ai massimi storici", base:"≈500 mila passeggeri nel 2024 (stima)",
      delta:"crescita continua", deltaCls:"up-good", deltaSub:"ferrovia ancora lenta", barPct:55, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"L'aeroporto San Francesco d'Assisi ha superato i record storici di traffico (circa mezzo milione di passeggeri annui, valore stimato dai comunicati SASE). I collegamenti ferroviari veloci con Roma e la riattivazione completa della ex Ferrovia Centrale Umbra restano invece in ritardo.",
      src:"SASE — Aeroporto internazionale dell'Umbria", url:"https://www.airport.umbria.it/", asof:"2024 (stima)" },
    { area:"Turismo", title:"Capitalizzare Giubileo e cammini",
      promise:"Obiettivo della giunta: trasformare i flussi del Giubileo 2025 e dei cammini francescani in turismo stabile (Assisi capitale spirituale).",
      cur:"in crescita", curLbl:"presenze turistiche, massimi storici recenti", base:"≈3 mln di presenze annue pre-Giubileo (stima)",
      delta:"effetto Giubileo", deltaCls:"up-good", deltaSub:"canonizzazione di Carlo Acutis", barPct:65, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Il 2025 giubilare ha portato flussi record ad Assisi e sui cammini, rafforzati dalla canonizzazione di Carlo Acutis. Valori indicati come stime: i consuntivi ufficiali sono pubblicati dal servizio turismo regionale.",
      src:"Regione Umbria — Osservatorio sul turismo", url:"https://www.regione.umbria.it/turismo-attivita-sportive", asof:"2025 (stima)" }
  ]
};
