window.DASH = window.DASH || {};
window.DASH.valledaosta = {
  meta: {
    nome: "Valle d'Aosta",
    area: "Nord",
    presidente: "Renzo Testolin",
    maggioranza: "autonomisti (UV, Autonomisti di Centro) e Forza Italia",
    stemma: "🦁"
  },
  ui: {
    h1: "Valle d'Aosta — Programma vs Realtà",
    sub: "Monitoraggio di 6 indicatori (4 comuni + 2 specifici) del programma della giunta autonomista confermata dopo le elezioni del 28 settembre 2025.",
    metaHtml: "Dati aggiornati a <b>luglio 2026</b> · Fonti: Ministero della Salute, ISTAT, ISPRA, Ministero dell'Interno · <b>Il valore (KPI) è misurato; lo «stato» è una valutazione. Correlazione ≠ causalità.</b>",
    searchPlaceholder: "Cerca indicatore…",
    chipsAll: "Tutte le aree",
    hint: "Clicca una scheda per aprire dettaglio, nota e fonte.",
    emptyMsg: "Nessun indicatore corrisponde ai filtri.",
    startLabel: "Punto di partenza",
    noteLabel: "Nota",
    sourceLabel: "Fonte",
    footerHtml: "<p><b>Metodologia.</b> Quattro stati: <span style='color:var(--green)'>In linea</span> (obiettivo raggiunto), <span style='color:var(--blue)'>In corso</span> (progressi coerenti con l'impegno), <span style='color:var(--amber)'>In ritardo</span> (progressi insufficienti), <span style='color:var(--red)'>Fermo</span> (nessun progresso misurabile). Gli indicatori misurano il contesto regionale: l'andamento non è attribuibile per intero all'azione della giunta (correlazione ≠ causalità). Dove indicato, i valori sono stime o arrotondamenti; i dati mancanti sono dichiarati.</p>"
  },
  status: {
    "in-linea": { label: "In linea",  cls: "s-green" },
    "in-corso": { label: "In corso",  cls: "s-blue"  },
    "ritardo":  { label: "In ritardo", cls: "s-amber" },
    "fermo":    { label: "Fermo",     cls: "s-red"   }
  },
  items: [
    { area:"Sanità", title:"Riportare i LEA alla sufficienza",
      promise:"Il programma autonomista promette il rafforzamento dell'ospedale Parini e della medicina territoriale, con incentivi contro la carenza di medici.",
      cur:"1/3", curLbl:"macro-aree LEA sopra la soglia di sufficienza (2023)", base:"insufficienze già rilevate nelle verifiche precedenti",
      delta:"2 aree critiche", deltaCls:"up-bad", deltaSub:"distrettuale e ospedaliera", barPct:30, barCol:"var(--red)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"Nel monitoraggio LEA 2023 la Valle d'Aosta risulta insufficiente in due macro-aree su tre (distrettuale e ospedaliera): è il caso più critico del Nord. Pesano le dimensioni ridotte del sistema sanitario e la difficoltà di reclutare personale.",
      src:"Ministero della Salute — Nuovo Sistema di Garanzia", url:"https://www.salute.gov.it/new/it/news-e-media/notizie/livelli-essenziali-di-assistenza-sintesi-dei-risultati-del-nuovo-sistema-di/", asof:"2023 (relazione 2025)" },
    { area:"Sicurezza", title:"Mantenere bassa la criminalità",
      promise:"Sicurezza dei piccoli comuni e presidio del territorio alpino.",
      cur:"≈2.900", curLbl:"delitti denunciati ogni 100.000 abitanti (2022, stima)", base:"media Italia: ≈3.800 ogni 100.000",
      delta:"-24% vs Italia", deltaCls:"up-good", deltaSub:"tra le regioni più sicure", barPct:78, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"La Valle d'Aosta resta ben sotto la media nazionale di denunce. Il valore è una stima arrotondata su dati ISTAT/Ministero dell'Interno 2022: i numeri assoluti molto piccoli rendono il tasso volatile da un anno all'altro.",
      src:"ISTAT — Delitti denunciati", url:"http://dati.istat.it/Index.aspx?DataSetCode=dccv_delittips", asof:"2022 (stima)" },
    { area:"Lavoro", title:"Piena occupazione e lotta allo spopolamento",
      promise:"Impegni su lavoro di montagna, sostegno alle imprese locali e residenzialità nei comuni alti.",
      cur:"70,9%", curLbl:"tasso di occupazione 15-64 anni (2023, arrotondato)", base:"media Italia: 61,5% (2023)",
      delta:"+9,4 pt vs Italia", deltaCls:"up-good", deltaSub:"tra le migliori in Italia", barPct:71, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Tasso di occupazione tra i più alti d'Italia, vicino alla piena occupazione. Il nodo è demografico: popolazione in calo e difficoltà a trovare manodopera stagionale. Valore arrotondato: verificare su dati.istat.it.",
      src:"ISTAT — Rilevazione sulle forze di lavoro", url:"https://noi-italia.istat.it/pagina.php?id=3&categoria=16&action=show&L=0", asof:"2023" },
    { area:"Ambiente", title:"Differenziata sopra il 65% e tutela alpina",
      promise:"Gestione unica regionale dei rifiuti e tutela dei ghiacciai nel programma di legislatura.",
      cur:"66,1%", curLbl:"raccolta differenziata (2022)", base:"obiettivo di legge: 65%",
      delta:"+1,1 pt vs obiettivo", deltaCls:"up-good", deltaSub:"appena sopra la soglia", barPct:66, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Obiettivo del 65% raggiunto. Sul fronte climatico la regione è tra le più esposte: i ghiacciai valdostani perdono massa a ritmi record secondo i monitoraggi ARPA VdA.",
      src:"ISPRA — Rapporto Rifiuti Urbani", url:"https://www.isprambiente.gov.it/it/istituto-informa/comunicati-stampa/anno-2024/rifiuti-urbani-nel-2023-cresce-dello-0-7-la-produzione", asof:"2022" },
    { area:"Energia", title:"Valorizzare l'idroelettrico (CVA)",
      promise:"Il programma punta su CVA e sulle rinnovabili per l'autonomia energetica della regione e nuove entrate pubbliche.",
      cur:"≈3 TWh", curLbl:"produzione idroelettrica annua CVA (stima)", base:"CVA interamente pubblica, piano industriale rinnovabili in corso",
      delta:"≈100% rinnovabile", deltaCls:"up-good", deltaSub:"produzione elettrica regionale", barPct:80, barCol:"var(--green)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"CVA (controllata dalla Regione) produce circa 3 TWh l'anno da idroelettrico e sta investendo in eolico e fotovoltaico fuori valle. Valore indicativo da bilanci societari: la produzione varia con l'idraulicità annuale. Resta aperto il tema nazionale delle concessioni idroelettriche.",
      src:"CVA S.p.A. — Bilancio e piano industriale", url:"https://www.cvaspa.it/", asof:"2024 (stima)" },
    { area:"Turismo", title:"Destagionalizzare il turismo alpino",
      promise:"Obiettivo di legislatura: crescita del turismo estivo e dei collegamenti (trenino Aosta-Pré-Saint-Didier, funivie).",
      cur:"≈3,6 mln", curLbl:"presenze turistiche annue (2023, stima)", base:"≈3,2 mln pre-pandemia (stima)",
      delta:"sopra il 2019", deltaCls:"up-good", deltaSub:"recupero completato", barPct:70, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Le presenze hanno superato i livelli pre-Covid con una quota crescente di turismo estivo. Valori stimati dai bollettini dell'Osservatorio regionale del turismo; il dato definitivo va verificato sulle statistiche regionali.",
      src:"Regione Valle d'Aosta — Osservatorio del turismo", url:"https://www.regione.vda.it/turismo_commercio_e_sport/osservatorio_del_turismo/default_i.aspx", asof:"2023 (stima)" }
  ]
};
