window.DASH = window.DASH || {};
window.DASH.veneto = {
  meta: {
    nome: "Veneto",
    area: "Nord",
    presidente: "Alberto Stefani",
    maggioranza: "centrodestra",
    stemma: "🦁"
  },
  ui: {
    h1: "Veneto — Programma vs Realtà",
    sub: "Monitoraggio di 6 indicatori (4 comuni + 2 specifici) del programma della giunta Stefani, eletta a novembre 2025 (64,4% dei voti) dopo i 15 anni di Zaia.",
    metaHtml: "Dati aggiornati a <b>luglio 2026</b> · Fonti: Ministero della Salute, ISTAT, ISPRA, Ministero dell'Interno · <b>Il valore (KPI) è misurato; lo «stato» è una valutazione. Correlazione ≠ causalità.</b>",
    searchPlaceholder: "Cerca indicatore…",
    chipsAll: "Tutte le aree",
    hint: "Clicca una scheda per aprire dettaglio, nota e fonte.",
    emptyMsg: "Nessun indicatore corrisponde ai filtri.",
    startLabel: "Punto di partenza",
    noteLabel: "Nota",
    sourceLabel: "Fonte",
    footerHtml: "<p><b>Metodologia.</b> Quattro stati: <span style='color:var(--green)'>In linea</span> (obiettivo raggiunto), <span style='color:var(--blue)'>In corso</span> (progressi coerenti con l'impegno), <span style='color:var(--amber)'>In ritardo</span> (progressi insufficienti), <span style='color:var(--red)'>Fermo</span> (nessun progresso misurabile). La giunta è in carica da pochi mesi: molti indicatori fotografano l'eredità della gestione precedente. Correlazione ≠ causalità. Dove indicato, i valori sono stime; i dati mancanti sono dichiarati.</p>"
  },
  status: {
    "in-linea": { label: "In linea",  cls: "s-green" },
    "in-corso": { label: "In corso",  cls: "s-blue"  },
    "ritardo":  { label: "In ritardo", cls: "s-amber" },
    "fermo":    { label: "Fermo",     cls: "s-red"   }
  },
  items: [
    { area:"Sanità", title:"Difendere il modello veneto e tagliare le attese",
      promise:"Il programma Stefani promette continuità col modello sanitario veneto, più medici di famiglia nei piccoli comuni e liste d'attesa ridotte.",
      cur:"3/3", curLbl:"macro-aree LEA sopra la soglia di sufficienza (2023)", base:"Regione storicamente ai vertici del monitoraggio",
      delta:"adempiente", deltaCls:"up-good", deltaSub:"tra i punteggi più alti", barPct:85, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Il Veneto è sufficiente in tutte le macro-aree LEA 2023 con punteggi ai vertici nazionali. La carenza di medici di medicina generale nelle aree montane e le attese per alcune specialistiche restano i punti deboli riconosciuti dallo stesso programma.",
      src:"Ministero della Salute — Nuovo Sistema di Garanzia", url:"https://www.salute.gov.it/new/it/news-e-media/notizie/livelli-essenziali-di-assistenza-sintesi-dei-risultati-del-nuovo-sistema-di/", asof:"2023 (relazione 2025)" },
    { area:"Sicurezza", title:"Sicurezza nelle città e nei capannoni",
      promise:"Impegni su polizia locale, controllo di vicinato e contrasto a furti e baby gang.",
      cur:"≈3.300", curLbl:"delitti denunciati ogni 100.000 abitanti (2022, stima)", base:"media Italia: ≈3.800 ogni 100.000",
      delta:"-13% vs Italia", deltaCls:"up-good", deltaSub:"sotto la media nazionale", barPct:68, barCol:"var(--green)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Denunce sotto la media nazionale, ma in crescita nei capoluoghi (Venezia e Padova sopra la media regionale). Valore stimato e arrotondato su dati ISTAT/Ministero dell'Interno 2022.",
      src:"ISTAT — Delitti denunciati", url:"http://dati.istat.it/Index.aspx?DataSetCode=dccv_delittips", asof:"2022 (stima)" },
    { area:"Lavoro", title:"Trattenere giovani e manodopera qualificata",
      promise:"Il programma punta su salari, casa e formazione tecnica per frenare l'emigrazione dei giovani laureati.",
      cur:"67,9%", curLbl:"tasso di occupazione 15-64 anni (2023, arrotondato)", base:"media Italia: 61,5% (2023)",
      delta:"+6,4 pt vs Italia", deltaCls:"up-good", deltaSub:"sopra la media nazionale", barPct:68, barCol:"var(--blue)",
      status:"in-corso", badge:"In corso", bCls:"b-blue",
      note:"Mercato del lavoro vicino al pieno impiego, con carenza diffusa di profili tecnici. Il saldo migratorio dei giovani qualificati verso l'estero resta negativo, ed è il vero obiettivo dichiarato della legislatura. Valore arrotondato.",
      src:"ISTAT — Rilevazione sulle forze di lavoro", url:"https://noi-italia.istat.it/pagina.php?id=3&categoria=16&action=show&L=0", asof:"2023" },
    { area:"Ambiente", title:"Prima regione per raccolta differenziata",
      promise:"Continuità nella gestione dei rifiuti e bonifica dei siti inquinati da PFAS, tema simbolo della regione.",
      cur:"77,7%", curLbl:"raccolta differenziata (2023)", base:"obiettivo di legge: 65%",
      delta:"+12,7 pt vs obiettivo", deltaCls:"up-good", deltaSub:"prima regione d'Italia", barPct:78, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Il Veneto è primo in Italia per raccolta differenziata (77,7% nel 2023). Sul fronte opposto pesa l'eredità dell'inquinamento da PFAS nelle province di Vicenza, Verona e Padova, con bonifiche ancora in corso.",
      src:"ISPRA — Rapporto Rifiuti Urbani 2024", url:"https://www.isprambiente.gov.it/it/istituto-informa/comunicati-stampa/anno-2024/rifiuti-urbani-nel-2023-cresce-dello-0-7-la-produzione", asof:"2023" },
    { area:"Autonomia", title:"Ottenere l'autonomia differenziata",
      promise:"Primo punto del programma Stefani (e bandiera storica della Lega veneta): firmare l'intesa Stato-Regione sulle materie dell'articolo 116 della Costituzione.",
      cur:"0", curLbl:"intese firmate; pre-intese in via di approvazione (luglio 2026)", base:"referendum 2017: 98% di sì; legge Calderoli approvata nel 2024",
      delta:"pre-intese approvate", deltaCls:"up-good", deltaSub:"Senato ha approvato il 16 luglio; attesa Camera", barPct:35, barCol:"var(--blue)",
      status:"ritardo", badge:"In ritardo", bCls:"b-amber",
      note:"A quasi nove anni dal referendum non è stata firmata alcuna intesa definitiva. Il Senato ha approvato il 16 luglio 2026 le risoluzioni sulle pre-intese Stato-Veneto (protezione civile, professioni, previdenza complementare, tutela salute). Attesa l'approvazione in Camera e successivo iter di sottoscrizione formale.",
      src:"Corte costituzionale — sentenza 192/2024; negoziato art. 116", url:"https://www.veronasera.it/politica/stefani-calderoli-manildo-audizione-autonomia-veneto-giugno-2026.html", asof:"luglio 2026" },
    { area:"Turismo", title:"Confermare il primato turistico italiano",
      promise:"Il programma punta a consolidare il primato di regione più visitata d'Italia, gestendo l'overtourism a Venezia e sulle Dolomiti (Olimpiadi 2026).",
      cur:"≈73 mln", curLbl:"presenze turistiche annue (2024, stima)", base:"≈71 mln nel 2023",
      delta:"record storico", deltaCls:"up-good", deltaSub:"prima regione d'Italia", barPct:85, barCol:"var(--green)",
      status:"in-linea", badge:"In linea", bCls:"b-green",
      note:"Il Veneto è la prima regione italiana per presenze turistiche, con record post-pandemia e l'effetto Olimpiadi invernali 2026 su Cortina. Valore stimato dai bollettini della Regione: il consuntivo ufficiale è pubblicato dall'ufficio statistica regionale.",
      src:"Regione Veneto — Statistiche sul turismo", url:"https://statistica.regione.veneto.it/", asof:"2024 (stima)" }
  ]
};
